type MCQ = { content: string; options: string[]; correct: number; explanation?: string };
type Essay = { content: string; explanation?: string; points?: number };

export const lawQ1 = {
  mcqs: [
    {
      content: 'Hiến pháp năm 2013 của Việt Nam được Quốc hội thông qua vào ngày nào?',
      options: [
        '28/11/2013',
        '02/04/2013',
        '19/06/2013',
        '01/01/2014',
      ],
      correct: 0,
      explanation: 'Hiến pháp 2013 được Quốc hội khóa XIII thông qua ngày 28/11/2013 tại kỳ họp thứ 6.',
    },
    {
      content: 'Theo Hiến pháp 2013, quyền lực nhà nước thuộc về ai?',
      options: [
        'Đảng Cộng sản Việt Nam',
        'Nhân dân',
        'Quốc hội',
        'Chính phủ',
      ],
      correct: 1,
      explanation: 'Điều 2 Hiến pháp 2013 quy định: "Nước Cộng hòa xã hội chủ nghĩa Việt Nam do Nhân dân làm chủ; tất cả quyền lực nhà nước thuộc về Nhân dân".',
    },
    {
      content: 'Hệ thống pháp luật Việt Nam thuộc dòng họ pháp luật nào?',
      options: [
        'Common Law (Thông luật)',
        'Civil Law (Luật dân sự)',
        'Luật Hồi giáo',
        'Luật tập quán',
      ],
      correct: 1,
      explanation: 'Việt Nam thuộc hệ thống Civil Law (dòng họ pháp luật châu Âu lục địa), chịu ảnh hưởng từ hệ thống pháp luật Pháp.',
    },
    {
      content: 'Nguồn của pháp luật Việt Nam KHÔNG bao gồm loại nào sau đây?',
      options: [
        'Văn bản quy phạm pháp luật',
        'Án lệ',
        'Điều ước quốc tế',
        'Phán quyết của tòa án nước ngoài',
      ],
      correct: 3,
      explanation: 'Phán quyết của tòa án nước ngoài không phải là nguồn của pháp luật Việt Nam. Nguồn bao gồm: văn bản QPPL, án lệ (từ 2015), điều ước quốc tế, tập quán pháp.',
    },
    {
      content: 'Văn bản quy phạm pháp luật có hiệu lực pháp lý cao nhất trong hệ thống pháp luật Việt Nam là gì?',
      options: [
        'Luật',
        'Nghị định',
        'Hiến pháp',
        'Pháp lệnh',
      ],
      correct: 2,
      explanation: 'Hiến pháp là đạo luật cơ bản, có hiệu lực pháp lý cao nhất. Mọi văn bản pháp luật khác phải phù hợp với Hiến pháp.',
    },
    {
      content: 'Theo Luật Ban hành văn bản quy phạm pháp luật 2015, cơ quan nào có thẩm quyền ban hành Nghị định?',
      options: [
        'Quốc hội',
        'Ủy ban Thường vụ Quốc hội',
        'Chính phủ',
        'Bộ trưởng',
      ],
      correct: 2,
      explanation: 'Nghị định là văn bản do Chính phủ ban hành để quy định chi tiết và hướng dẫn thi hành luật, pháp lệnh.',
    },
    {
      content: 'Năng lực pháp luật dân sự của cá nhân phát sinh từ khi nào?',
      options: [
        'Từ khi đủ 18 tuổi',
        'Từ khi sinh ra',
        'Từ khi đủ 15 tuổi',
        'Từ khi được cấp CMND/CCCD',
      ],
      correct: 1,
      explanation: 'Theo Điều 16 BLDS 2015, năng lực pháp luật dân sự của cá nhân có từ khi người đó sinh ra và chấm dứt khi người đó chết.',
    },
    {
      content: 'Theo Bộ luật Dân sự 2015, người từ đủ bao nhiêu tuổi trở lên có năng lực hành vi dân sự đầy đủ?',
      options: [
        '16 tuổi',
        '15 tuổi',
        '18 tuổi',
        '21 tuổi',
      ],
      correct: 2,
      explanation: 'Điều 20 BLDS 2015: Người thành niên (từ đủ 18 tuổi trở lên) có năng lực hành vi dân sự đầy đủ, trừ trường hợp bị mất hoặc hạn chế năng lực hành vi dân sự.',
    },
    {
      content: 'Thời hiệu khởi kiện để yêu cầu bồi thường thiệt hại ngoài hợp đồng theo BLDS 2015 là bao lâu?',
      options: [
        '01 năm',
        '02 năm',
        '03 năm',
        '05 năm',
      ],
      correct: 2,
      explanation: 'Điều 588 BLDS 2015 quy định thời hiệu khởi kiện yêu cầu bồi thường thiệt hại là 03 năm kể từ ngày người có quyền yêu cầu biết hoặc phải biết quyền, lợi ích hợp pháp bị xâm phạm.',
    },
    {
      content: 'Theo Bộ luật Lao động 2019, độ tuổi lao động tối thiểu là bao nhiêu?',
      options: [
        '13 tuổi',
        '15 tuổi',
        '16 tuổi',
        '18 tuổi',
      ],
      correct: 1,
      explanation: 'Điều 143 BLLĐ 2019 quy định người lao động chưa thành niên là người lao động dưới 18 tuổi; độ tuổi lao động tối thiểu là đủ 15 tuổi.',
    },
    {
      content: 'Theo Bộ luật Lao động 2019, thời gian thử việc đối với công việc có chức danh nghề cần trình độ chuyên môn từ cao đẳng trở lên tối đa là bao lâu?',
      options: [
        '30 ngày',
        '60 ngày',
        '90 ngày',
        '180 ngày',
      ],
      correct: 1,
      explanation: 'Điều 25 BLLĐ 2019: Thời gian thử việc không quá 60 ngày đối với công việc có chức danh nghề nghiệp cần trình độ chuyên môn, kỹ thuật từ cao đẳng trở lên.',
    },
    {
      content: 'Theo BLLĐ 2019, người sử dụng lao động phải báo trước cho người lao động ít nhất bao nhiêu ngày khi đơn phương chấm dứt hợp đồng lao động không xác định thời hạn?',
      options: [
        '15 ngày',
        '30 ngày',
        '45 ngày',
        '60 ngày',
      ],
      correct: 2,
      explanation: 'Điều 36 BLLĐ 2019: Người sử dụng lao động phải báo trước ít nhất 45 ngày đối với HĐLĐ không xác định thời hạn.',
    },
    {
      content: 'Tuổi nghỉ hưu của lao động nam theo lộ trình Bộ luật Lao động 2019 đến năm 2028 là bao nhiêu?',
      options: [
        '60 tuổi',
        '61 tuổi',
        '62 tuổi',
        '63 tuổi',
      ],
      correct: 2,
      explanation: 'Điều 169 BLLĐ 2019 quy định tuổi nghỉ hưu của lao động nam đạt 62 tuổi vào năm 2028 (tăng dần mỗi năm 3 tháng từ 2021).',
    },
    {
      content: 'Theo Bộ luật Hình sự 2015, tuổi chịu trách nhiệm hình sự đầy đủ là từ đủ bao nhiêu tuổi?',
      options: [
        '14 tuổi',
        '16 tuổi',
        '18 tuổi',
        '21 tuổi',
      ],
      correct: 1,
      explanation: 'Điều 12 BLHS 2015: Người từ đủ 16 tuổi trở lên phải chịu trách nhiệm hình sự về mọi tội phạm. Người từ đủ 14 đến dưới 16 tuổi chỉ chịu TNHS về tội phạm rất nghiêm trọng, đặc biệt nghiêm trọng.',
    },
    {
      content: 'Theo BLHS 2015, hình phạt nào KHÔNG thuộc hệ thống hình phạt chính?',
      options: [
        'Cảnh cáo',
        'Phạt tiền',
        'Tịch thu tài sản',
        'Tù có thời hạn',
      ],
      correct: 2,
      explanation: 'Tịch thu tài sản là hình phạt bổ sung (Điều 32 BLHS 2015). Hình phạt chính gồm: cảnh cáo, phạt tiền, cải tạo không giam giữ, trục xuất, tù có thời hạn, tù chung thân, tử hình.',
    },
    {
      content: 'Quan hệ pháp luật bao gồm mấy thành phần cơ bản?',
      options: [
        '2 thành phần',
        '3 thành phần',
        '4 thành phần',
        '5 thành phần',
      ],
      correct: 1,
      explanation: 'Quan hệ pháp luật gồm 3 thành phần: chủ thể, nội dung (quyền và nghĩa vụ pháp lý), và khách thể (lợi ích mà các chủ thể hướng tới).',
    },
    {
      content: 'Sự kiện pháp lý là gì?',
      options: [
        'Mọi sự kiện xảy ra trong đời sống xã hội',
        'Sự kiện thực tế mà pháp luật gắn với việc phát sinh, thay đổi hoặc chấm dứt quan hệ pháp luật',
        'Sự kiện do cơ quan nhà nước tạo ra',
        'Sự kiện được ghi nhận trong văn bản pháp luật',
      ],
      correct: 1,
      explanation: 'Sự kiện pháp lý là những sự kiện xảy ra trong thực tế mà pháp luật dự liệu, gắn với sự phát sinh, thay đổi hoặc chấm dứt quan hệ pháp luật.',
    },
    {
      content: 'Trách nhiệm pháp lý hành chính được áp dụng đối với chủ thể nào?',
      options: [
        'Chỉ cá nhân',
        'Chỉ tổ chức',
        'Cá nhân và tổ chức',
        'Chỉ cơ quan nhà nước',
      ],
      correct: 2,
      explanation: 'Trách nhiệm pháp lý hành chính (xử phạt vi phạm hành chính) được áp dụng đối với cả cá nhân và tổ chức có hành vi vi phạm hành chính.',
    },
    {
      content: 'Theo Luật Xử lý vi phạm hành chính 2012 (sửa đổi 2020), mức phạt tiền tối đa trong lĩnh vực giao thông đường bộ đối với cá nhân là bao nhiêu?',
      options: [
        '40 triệu đồng',
        '75 triệu đồng',
        '100 triệu đồng',
        '150 triệu đồng',
      ],
      correct: 0,
      explanation: 'Theo quy định, mức phạt tiền tối đa trong lĩnh vực giao thông đường bộ đối với cá nhân là 40 triệu đồng (đối với tổ chức là gấp đôi).',
    },
    {
      content: 'Theo Luật Sở hữu trí tuệ Việt Nam, thời hạn bảo hộ quyền tác giả đối với tác phẩm điện ảnh là bao lâu kể từ khi công bố lần đầu?',
      options: [
        '25 năm',
        '50 năm',
        '75 năm',
        'Suốt đời tác giả và 50 năm sau khi tác giả chết',
      ],
      correct: 2,
      explanation: 'Điều 27 Luật SHTT quy định quyền tài sản đối với tác phẩm điện ảnh được bảo hộ 75 năm kể từ khi tác phẩm được công bố lần đầu tiên.',
    },
    {
      content: 'Sáng chế được bảo hộ dưới hình thức Bằng độc quyền sáng chế có thời hạn bao lâu?',
      options: [
        '10 năm kể từ ngày nộp đơn',
        '15 năm kể từ ngày nộp đơn',
        '20 năm kể từ ngày nộp đơn',
        '25 năm kể từ ngày nộp đơn',
      ],
      correct: 2,
      explanation: 'Điều 93 Luật SHTT: Bằng độc quyền sáng chế có hiệu lực từ ngày cấp đến hết 20 năm kể từ ngày nộp đơn.',
    },
    {
      content: 'Luật An ninh mạng 2018 của Việt Nam có hiệu lực thi hành từ ngày nào?',
      options: [
        '01/01/2018',
        '12/06/2018',
        '01/01/2019',
        '01/07/2019',
      ],
      correct: 2,
      explanation: 'Luật An ninh mạng 2018 được Quốc hội thông qua ngày 12/6/2018 và có hiệu lực thi hành từ ngày 01/01/2019.',
    },
    {
      content: 'Theo Luật An ninh mạng 2018, doanh nghiệp trong nước và ngoài nước cung cấp dịch vụ trên mạng viễn thông tại Việt Nam phải thực hiện nghĩa vụ nào?',
      options: [
        'Đặt máy chủ tại Việt Nam (đối với trường hợp luật quy định)',
        'Sử dụng tiếng Việt trong mọi giao diện',
        'Đóng thuế gấp đôi doanh nghiệp trong nước',
        'Không được mã hóa dữ liệu',
      ],
      correct: 0,
      explanation: 'Điều 26 Luật An ninh mạng 2018 quy định doanh nghiệp phải lưu trữ dữ liệu và đặt chi nhánh hoặc văn phòng đại diện tại Việt Nam trong các trường hợp luật quy định.',
    },
    {
      content: 'Luật Giao dịch điện tử 2023 (thay thế Luật GDĐT 2005) có hiệu lực từ ngày nào?',
      options: [
        '01/01/2024',
        '01/07/2024',
        '01/01/2025',
        '22/06/2023',
      ],
      correct: 1,
      explanation: 'Luật Giao dịch điện tử 2023 có hiệu lực thi hành từ ngày 01/7/2024.',
    },
    {
      content: 'Theo Luật Giao dịch điện tử, chữ ký điện tử có giá trị pháp lý khi đáp ứng điều kiện nào?',
      options: [
        'Được tạo bằng phần mềm bất kỳ',
        'Được xác nhận bởi tổ chức chứng thực chữ ký điện tử',
        'Chỉ cần do người ký tạo ra',
        'Được in ra giấy và đóng dấu',
      ],
      correct: 1,
      explanation: 'Chữ ký điện tử có giá trị pháp lý khi được tạo bằng phương tiện tạo chữ ký điện tử và được xác nhận bởi tổ chức chứng thực chữ ký điện tử.',
    },
    {
      content: 'Hợp đồng dân sự vô hiệu khi nào?',
      options: [
        'Khi một bên không thực hiện đúng nghĩa vụ',
        'Khi vi phạm điều kiện có hiệu lực theo quy định pháp luật',
        'Khi hết thời hạn hợp đồng',
        'Khi một bên yêu cầu chấm dứt',
      ],
      correct: 1,
      explanation: 'Hợp đồng vô hiệu khi vi phạm các điều kiện có hiệu lực: chủ thể không có năng lực, không tự nguyện, vi phạm điều cấm, trái đạo đức xã hội, không đúng hình thức luật định.',
    },
    {
      content: 'Theo BLDS 2015, hợp đồng được giao kết vào thời điểm nào?',
      options: [
        'Khi bên đề nghị gửi đề nghị',
        'Khi bên được đề nghị nhận được đề nghị',
        'Khi bên được đề nghị trả lời chấp nhận',
        'Khi bên đề nghị nhận được trả lời chấp nhận giao kết',
      ],
      correct: 3,
      explanation: 'Điều 400 BLDS 2015: Hợp đồng được giao kết vào thời điểm bên đề nghị nhận được chấp nhận giao kết (trừ trường hợp các bên có thỏa thuận khác hoặc pháp luật có quy định khác).',
    },
    {
      content: 'Pháp nhân phải có đủ các điều kiện nào theo BLDS 2015?',
      options: [
        'Được thành lập hợp pháp, có cơ cấu tổ chức, có tài sản độc lập, nhân danh mình tham gia quan hệ pháp luật',
        'Có trụ sở, có vốn, có người đại diện',
        'Được nhà nước công nhận, có tài sản, có nhân viên',
        'Có giấy phép kinh doanh và vốn điều lệ',
      ],
      correct: 0,
      explanation: 'Điều 74 BLDS 2015 quy định 4 điều kiện: (1) được thành lập theo quy định; (2) có cơ cấu tổ chức; (3) có tài sản độc lập và tự chịu trách nhiệm; (4) nhân danh mình tham gia quan hệ pháp luật.',
    },
    {
      content: 'Luật Doanh nghiệp 2020 quy định có mấy loại hình doanh nghiệp?',
      options: [
        '3 loại',
        '4 loại',
        '5 loại',
        '6 loại',
      ],
      correct: 2,
      explanation: 'Luật Doanh nghiệp 2020 quy định 5 loại hình: Doanh nghiệp tư nhân, Công ty TNHH 1 thành viên, Công ty TNHH 2 thành viên trở lên, Công ty cổ phần, Công ty hợp danh.',
    },
    {
      content: 'Công ty cổ phần phải có tối thiểu bao nhiêu cổ đông sáng lập?',
      options: [
        '1 cổ đông',
        '2 cổ đông',
        '3 cổ đông',
        '5 cổ đông',
      ],
      correct: 2,
      explanation: 'Điều 120 Luật Doanh nghiệp 2020: Công ty cổ phần phải có ít nhất 03 cổ đông sáng lập và không hạn chế số lượng tối đa.',
    },
    {
      content: 'Theo Hiến pháp 2013, Quốc hội Việt Nam có nhiệm kỳ bao nhiêu năm?',
      options: [
        '4 năm',
        '5 năm',
        '6 năm',
        '7 năm',
      ],
      correct: 1,
      explanation: 'Điều 71 Hiến pháp 2013 quy định nhiệm kỳ của mỗi khóa Quốc hội là 05 năm.',
    },
    {
      content: 'Quyền con người và quyền công dân được quy định tại chương mấy của Hiến pháp 2013?',
      options: [
        'Chương I',
        'Chương II',
        'Chương III',
        'Chương IV',
      ],
      correct: 1,
      explanation: 'Chương II Hiến pháp 2013 (từ Điều 14 đến Điều 49) quy định về quyền con người, quyền và nghĩa vụ cơ bản của công dân.',
    },
    {
      content: 'Theo Hiến pháp 2013, công dân Việt Nam có nghĩa vụ nào sau đây?',
      options: [
        'Nghĩa vụ tham gia Đảng Cộng sản',
        'Nghĩa vụ quân sự và tham gia xây dựng nền quốc phòng toàn dân',
        'Nghĩa vụ theo đạo',
        'Nghĩa vụ kinh doanh',
      ],
      correct: 1,
      explanation: 'Điều 45 Hiến pháp 2013: "Bảo vệ Tổ quốc là nghĩa vụ thiêng liêng và quyền cao quý của công dân. Công dân phải thực hiện nghĩa vụ quân sự và tham gia xây dựng nền quốc phòng toàn dân."',
    },
    {
      content: 'Quy phạm pháp luật gồm mấy bộ phận cấu thành?',
      options: [
        '2 bộ phận',
        '3 bộ phận',
        '4 bộ phận',
        '5 bộ phận',
      ],
      correct: 1,
      explanation: 'Quy phạm pháp luật gồm 3 bộ phận: giả định (điều kiện, hoàn cảnh), quy định (quy tắc xử sự), và chế tài (hậu quả pháp lý bất lợi khi vi phạm).',
    },
    {
      content: 'Hình thức thực hiện pháp luật nào đòi hỏi chủ thể phải thực hiện hành vi tích cực?',
      options: [
        'Tuân thủ pháp luật',
        'Thi hành pháp luật',
        'Sử dụng pháp luật',
        'Áp dụng pháp luật',
      ],
      correct: 1,
      explanation: 'Thi hành (chấp hành) pháp luật đòi hỏi chủ thể thực hiện nghĩa vụ bằng hành vi tích cực (ví dụ: nộp thuế, đăng ký kinh doanh). Tuân thủ là không làm điều cấm.',
    },
    {
      content: 'Vi phạm pháp luật phải có đủ mấy dấu hiệu cơ bản?',
      options: [
        '2 dấu hiệu',
        '3 dấu hiệu',
        '4 dấu hiệu',
        '5 dấu hiệu',
      ],
      correct: 2,
      explanation: 'Vi phạm pháp luật có 4 dấu hiệu: (1) hành vi (hành động/không hành động); (2) trái pháp luật; (3) có lỗi (cố ý/vô ý); (4) do chủ thể có năng lực trách nhiệm pháp lý thực hiện.',
    },
    {
      content: 'Lỗi cố ý trực tiếp trong luật hình sự là gì?',
      options: [
        'Người phạm tội nhận thức được hành vi nguy hiểm nhưng tin rằng hậu quả không xảy ra',
        'Người phạm tội nhận thức rõ hành vi nguy hiểm, thấy trước hậu quả và mong muốn hậu quả xảy ra',
        'Người phạm tội không nhận thức được hành vi nguy hiểm',
        'Người phạm tội bị ép buộc thực hiện hành vi',
      ],
      correct: 1,
      explanation: 'Điều 10 BLHS 2015: Cố ý trực tiếp là người phạm tội nhận thức rõ hành vi của mình là nguy hiểm cho xã hội, thấy trước hậu quả và mong muốn hậu quả đó xảy ra.',
    },
    {
      content: 'Thẩm quyền giải thích Hiến pháp, luật, pháp lệnh thuộc về cơ quan nào?',
      options: [
        'Tòa án nhân dân tối cao',
        'Viện kiểm sát nhân dân tối cao',
        'Ủy ban Thường vụ Quốc hội',
        'Chính phủ',
      ],
      correct: 2,
      explanation: 'Điều 74 Hiến pháp 2013 quy định Ủy ban Thường vụ Quốc hội có thẩm quyền giải thích Hiến pháp, luật, pháp lệnh.',
    },
    {
      content: 'Theo Luật Doanh nghiệp 2020, doanh nghiệp tư nhân có đặc điểm gì?',
      options: [
        'Do nhiều cá nhân làm chủ',
        'Chủ sở hữu chịu trách nhiệm hữu hạn',
        'Do một cá nhân làm chủ và chịu trách nhiệm bằng toàn bộ tài sản',
        'Có thể phát hành cổ phiếu',
      ],
      correct: 2,
      explanation: 'Điều 188 Luật DN 2020: Doanh nghiệp tư nhân do một cá nhân làm chủ và tự chịu trách nhiệm bằng toàn bộ tài sản của mình về mọi hoạt động của doanh nghiệp.',
    },
    {
      content: 'Nhãn hiệu được bảo hộ theo Luật Sở hữu trí tuệ có thời hạn bao lâu và có thể gia hạn không?',
      options: [
        '10 năm, được gia hạn nhiều lần liên tiếp, mỗi lần 10 năm',
        '20 năm, không được gia hạn',
        '15 năm, được gia hạn 1 lần',
        '10 năm, không được gia hạn',
      ],
      correct: 0,
      explanation: 'Điều 93 Luật SHTT: Giấy chứng nhận đăng ký nhãn hiệu có hiệu lực 10 năm kể từ ngày nộp đơn, có thể gia hạn nhiều lần liên tiếp, mỗi lần 10 năm.',
    },
  ] as MCQ[],
  essays: [
    {
      content: 'Phân tích nguyên tắc "Quyền lực nhà nước là thống nhất, có sự phân công, phối hợp, kiểm soát giữa các cơ quan nhà nước trong việc thực hiện các quyền lập pháp, hành pháp, tư pháp" theo Hiến pháp 2013. Liên hệ thực tiễn tổ chức bộ máy nhà nước Việt Nam hiện nay.',
      points: 4,
      explanation: 'Cần phân tích Điều 2 Hiến pháp 2013; so sánh với học thuyết tam quyền phân lập; chỉ ra đặc thù của Việt Nam: thống nhất quyền lực ở Quốc hội, Chính phủ thực hiện hành pháp, TAND thực hiện tư pháp; cơ chế kiểm soát quyền lực.',
    },
    {
      content: 'Trình bày khái niệm, đặc điểm của quan hệ pháp luật. Phân tích các thành phần của quan hệ pháp luật và cho ví dụ minh họa cụ thể trong lĩnh vực dân sự.',
      points: 3,
      explanation: 'Trả lời cần nêu: khái niệm QHPL (quan hệ xã hội được QPPL điều chỉnh); đặc điểm (tính ý chí, mang tính giai cấp, được nhà nước bảo đảm); 3 thành phần (chủ thể, nội dung, khách thể); ví dụ hợp đồng mua bán.',
    },
    {
      content: 'So sánh trách nhiệm pháp lý hình sự và trách nhiệm pháp lý hành chính. Nêu ý nghĩa của việc phân biệt hai loại trách nhiệm này trong thực tiễn áp dụng pháp luật.',
      points: 3,
      explanation: 'Cần so sánh: cơ sở phát sinh (tội phạm vs vi phạm hành chính); chủ thể áp dụng (Tòa án vs cơ quan hành chính); hình thức chế tài (hình phạt vs xử phạt VPHC); hậu quả pháp lý (án tích vs không án tích); ý nghĩa phân biệt.',
    },
    {
      content: 'Phân tích quyền tự do kinh doanh của công dân theo Hiến pháp 2013 và Luật Doanh nghiệp 2020. Những hạn chế nào được pháp luật đặt ra đối với quyền này và tại sao?',
      points: 4,
      explanation: 'Cần phân tích Điều 33 HP 2013, Điều 7 Luật DN 2020; quyền lựa chọn ngành nghề, hình thức kinh doanh; hạn chế: ngành nghề cấm, ngành có điều kiện (Phụ lục IV Luật Đầu tư); lý do: bảo vệ an ninh, sức khỏe, đạo đức.',
    },
    {
      content: 'Trình bày các hình thức thực hiện pháp luật. Phân tích sự khác biệt giữa "áp dụng pháp luật" với các hình thức khác và cho ví dụ thực tiễn.',
      points: 3,
      explanation: 'Bốn hình thức: tuân thủ (không làm điều cấm), thi hành (thực hiện nghĩa vụ), sử dụng (thực hiện quyền), áp dụng (cơ quan nhà nước ban hành quyết định cá biệt). Áp dụng PL khác biệt: chỉ CQNN/người có thẩm quyền mới thực hiện được.',
    },
    {
      content: 'Phân tích chế định hợp đồng lao động theo Bộ luật Lao động 2019: các loại hợp đồng, nội dung bắt buộc, và các trường hợp chấm dứt hợp đồng lao động hợp pháp.',
      points: 4,
      explanation: 'Cần trình bày: 2 loại HĐLĐ (xác định thời hạn và không xác định thời hạn - Điều 20); nội dung bắt buộc (Điều 21); chấm dứt HĐLĐ (Điều 34-41): thỏa thuận, đơn phương của NLĐ/NSDLĐ, hết hạn, sa thải.',
    },
    {
      content: 'Phân tích các điều kiện để một hợp đồng dân sự có hiệu lực theo Bộ luật Dân sự 2015. Nêu hậu quả pháp lý khi hợp đồng bị tuyên vô hiệu.',
      points: 3,
      explanation: 'Điều kiện (Điều 117 BLDS): chủ thể có năng lực, tự nguyện, mục đích và nội dung không vi phạm điều cấm/đạo đức, hình thức phù hợp. Hậu quả vô hiệu (Điều 131): không phát sinh quyền/nghĩa vụ, hoàn trả, bồi thường thiệt hại.',
    },
    {
      content: 'Trình bày và phân tích các quy định của Luật An ninh mạng 2018 về bảo vệ thông tin cá nhân trên không gian mạng. Đánh giá tác động của các quy định này đối với doanh nghiệp công nghệ tại Việt Nam.',
      points: 5,
      explanation: 'Cần phân tích: Điều 16, 17, 26 Luật ANM; nghĩa vụ lưu trữ dữ liệu; bảo vệ thông tin cá nhân; xử lý vi phạm; tác động: chi phí tuân thủ, hạ tầng lưu trữ, ảnh hưởng đến doanh nghiệp FDI và startup.',
    },
    {
      content: 'So sánh quyền sở hữu trí tuệ đối với sáng chế và nhãn hiệu theo Luật Sở hữu trí tuệ Việt Nam. Phân tích vai trò của bảo hộ sở hữu trí tuệ trong nền kinh tế thị trường.',
      points: 4,
      explanation: 'So sánh: đối tượng, điều kiện bảo hộ, thời hạn (20 năm vs 10 năm gia hạn), phạm vi quyền, thủ tục đăng ký. Vai trò: khuyến khích sáng tạo, bảo vệ đầu tư R&D, cạnh tranh lành mạnh, hội nhập quốc tế (TRIPs).',
    },
    {
      content: 'Phân tích giá trị pháp lý của giao dịch điện tử theo Luật Giao dịch điện tử 2023. Trình bày các điều kiện để thông điệp dữ liệu có giá trị pháp lý như văn bản giấy và ý nghĩa thực tiễn trong thương mại điện tử.',
      points: 4,
      explanation: 'Cần phân tích: nguyên tắc không phân biệt đối xử (Điều 6); điều kiện thông điệp dữ liệu có giá trị (Điều 10-12); chữ ký điện tử, chữ ký số; hợp đồng điện tử; ý nghĩa: thúc đẩy TMĐT, chuyển đổi số, giảm chi phí giao dịch.',
    },
  ] as Essay[],
};

export const lawQ2 = {
  mcqs: [
    {
      content: 'Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam là nhà nước pháp quyền xã hội chủ nghĩa được quy định tại điều nào của Hiến pháp 2013?',
      options: [
        'Điều 1',
        'Điều 2',
        'Điều 3',
        'Điều 4',
      ],
      correct: 1,
      explanation: 'Điều 2 Hiến pháp 2013 khẳng định: "Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam là nhà nước pháp quyền xã hội chủ nghĩa của Nhân dân, do Nhân dân, vì Nhân dân."',
    },
    {
      content: 'Theo Hiến pháp 2013, cơ quan nào là cơ quan hành chính nhà nước cao nhất?',
      options: [
        'Quốc hội',
        'Chủ tịch nước',
        'Chính phủ',
        'Tòa án nhân dân tối cao',
      ],
      correct: 2,
      explanation: 'Điều 94 Hiến pháp 2013: "Chính phủ là cơ quan hành chính nhà nước cao nhất của nước Cộng hòa xã hội chủ nghĩa Việt Nam, thực hiện quyền hành pháp."',
    },
    {
      content: 'Pháp luật khác với đạo đức ở điểm nào cơ bản nhất?',
      options: [
        'Pháp luật do nhà nước ban hành và bảo đảm thực hiện bằng quyền lực nhà nước',
        'Pháp luật quy định nhiều vấn đề hơn đạo đức',
        'Pháp luật xuất hiện trước đạo đức',
        'Pháp luật chỉ áp dụng cho công dân',
      ],
      correct: 0,
      explanation: 'Đặc trưng cơ bản nhất của pháp luật phân biệt với các quy phạm xã hội khác là tính quyền lực nhà nước: do nhà nước ban hành hoặc thừa nhận và bảo đảm thực hiện bằng sức mạnh cưỡng chế nhà nước.',
    },
    {
      content: 'Thuộc tính nào KHÔNG phải là thuộc tính cơ bản của pháp luật?',
      options: [
        'Tính quy phạm phổ biến',
        'Tính xác định chặt chẽ về mặt hình thức',
        'Tính được bảo đảm thực hiện bằng nhà nước',
        'Tính tự nguyện',
      ],
      correct: 3,
      explanation: 'Ba thuộc tính cơ bản của pháp luật: tính quy phạm phổ biến, tính xác định chặt chẽ về hình thức, tính được bảo đảm thực hiện bằng nhà nước. Tính tự nguyện là đặc trưng của đạo đức.',
    },
    {
      content: 'Chế tài trong quy phạm pháp luật là gì?',
      options: [
        'Điều kiện áp dụng quy phạm',
        'Quy tắc xử sự mà chủ thể phải tuân theo',
        'Hậu quả pháp lý bất lợi áp dụng đối với chủ thể vi phạm',
        'Quyền lợi của chủ thể',
      ],
      correct: 2,
      explanation: 'Chế tài là bộ phận xác định hậu quả pháp lý bất lợi mà nhà nước dự kiến áp dụng đối với chủ thể không thực hiện đúng phần quy định của quy phạm pháp luật.',
    },
    {
      content: 'Văn bản nào sau đây KHÔNG phải là văn bản quy phạm pháp luật?',
      options: [
        'Nghị quyết của Quốc hội',
        'Thông tư của Bộ trưởng',
        'Quyết định xử phạt vi phạm hành chính',
        'Nghị định của Chính phủ',
      ],
      correct: 2,
      explanation: 'Quyết định xử phạt VPHC là văn bản áp dụng pháp luật (văn bản cá biệt), không phải văn bản quy phạm pháp luật vì chỉ áp dụng cho một trường hợp cụ thể, không mang tính quy phạm phổ biến.',
    },
    {
      content: 'Theo Luật Ban hành VBQPPL 2015, văn bản quy phạm pháp luật có hiệu lực trở về trước (hồi tố) được áp dụng trong trường hợp nào?',
      options: [
        'Mọi trường hợp đều được hồi tố',
        'Chỉ khi cần thiết để bảo đảm lợi ích của nhà nước',
        'Khi cần thiết, không quy định trách nhiệm pháp lý mới hoặc nặng hơn',
        'Không bao giờ được phép hồi tố',
      ],
      correct: 2,
      explanation: 'Điều 152 Luật Ban hành VBQPPL 2015: Chỉ trong trường hợp cần thiết và không được quy định trách nhiệm pháp lý mới hoặc trách nhiệm pháp lý nặng hơn.',
    },
    {
      content: 'Năng lực hành vi dân sự của người từ đủ 6 tuổi đến chưa đủ 15 tuổi theo BLDS 2015 như thế nào?',
      options: [
        'Không có năng lực hành vi dân sự',
        'Có năng lực hành vi dân sự đầy đủ',
        'Có năng lực hành vi dân sự một phần (giao dịch phục vụ nhu cầu sinh hoạt hàng ngày phù hợp lứa tuổi)',
        'Bị hạn chế năng lực hành vi dân sự',
      ],
      correct: 2,
      explanation: 'Điều 21 BLDS 2015: Người từ đủ 6 tuổi đến chưa đủ 15 tuổi có thể tự mình xác lập, thực hiện giao dịch dân sự phục vụ nhu cầu sinh hoạt hàng ngày phù hợp với lứa tuổi.',
    },
    {
      content: 'Quyền sở hữu bao gồm những quyền năng nào theo BLDS 2015?',
      options: [
        'Quyền chiếm hữu và quyền sử dụng',
        'Quyền chiếm hữu, quyền sử dụng và quyền định đoạt',
        'Quyền sử dụng và quyền định đoạt',
        'Quyền chiếm hữu và quyền định đoạt',
      ],
      correct: 1,
      explanation: 'Điều 158 BLDS 2015: Quyền sở hữu bao gồm quyền chiếm hữu, quyền sử dụng và quyền định đoạt tài sản của chủ sở hữu theo quy định của pháp luật.',
    },
    {
      content: 'Thừa kế theo pháp luật được chia thành mấy hàng thừa kế?',
      options: [
        '2 hàng',
        '3 hàng',
        '4 hàng',
        '5 hàng',
      ],
      correct: 1,
      explanation: 'Điều 651 BLDS 2015 quy định 3 hàng thừa kế: Hàng thứ nhất (vợ/chồng, cha mẹ đẻ/nuôi, con đẻ/nuôi); Hàng thứ hai (ông bà, anh chị em ruột, cháu ruột); Hàng thứ ba (cụ, bác/chú/cô/dì/cậu ruột).',
    },
    {
      content: 'Theo BLLĐ 2019, hợp đồng lao động được giao kết theo mấy loại?',
      options: [
        '2 loại',
        '3 loại',
        '4 loại',
        '5 loại',
      ],
      correct: 0,
      explanation: 'Điều 20 BLLĐ 2019 quy định 2 loại HĐLĐ: (1) Hợp đồng lao động không xác định thời hạn; (2) Hợp đồng lao động xác định thời hạn (không quá 36 tháng).',
    },
    {
      content: 'Theo BLLĐ 2019, người lao động được nghỉ phép năm tối thiểu bao nhiêu ngày đối với điều kiện lao động bình thường?',
      options: [
        '10 ngày',
        '12 ngày',
        '14 ngày',
        '16 ngày',
      ],
      correct: 1,
      explanation: 'Điều 113 BLLĐ 2019: Người lao động làm việc đủ 12 tháng được nghỉ hằng năm, hưởng nguyên lương tối thiểu 12 ngày làm việc đối với điều kiện lao động bình thường.',
    },
    {
      content: 'Thời giờ làm việc bình thường theo BLLĐ 2019 không quá bao nhiêu giờ trong một ngày?',
      options: [
        '6 giờ',
        '8 giờ',
        '10 giờ',
        '12 giờ',
      ],
      correct: 1,
      explanation: 'Điều 105 BLLĐ 2019: Thời giờ làm việc bình thường không quá 08 giờ trong 01 ngày và không quá 48 giờ trong 01 tuần.',
    },
    {
      content: 'Theo BLLĐ 2019, lao động nữ mang thai được nghỉ thai sản bao nhiêu tháng?',
      options: [
        '4 tháng',
        '5 tháng',
        '6 tháng',
        '7 tháng',
      ],
      correct: 2,
      explanation: 'Điều 139 BLLĐ 2019: Lao động nữ được nghỉ thai sản trước và sau khi sinh con là 06 tháng; trường hợp sinh đôi trở lên thì tính từ con thứ hai, cứ mỗi con được nghỉ thêm 01 tháng.',
    },
    {
      content: 'Tội phạm được phân loại thành mấy loại theo BLHS 2015?',
      options: [
        '2 loại',
        '3 loại',
        '4 loại',
        '5 loại',
      ],
      correct: 2,
      explanation: 'Điều 9 BLHS 2015 phân loại tội phạm thành 4 loại: tội phạm ít nghiêm trọng, tội phạm nghiêm trọng, tội phạm rất nghiêm trọng, tội phạm đặc biệt nghiêm trọng.',
    },
    {
      content: 'Phòng vệ chính đáng theo BLHS 2015 là hành vi thuộc trường hợp nào?',
      options: [
        'Tấn công trước để ngăn ngừa nguy hiểm',
        'Chống trả lại hành vi xâm phạm tính mạng, sức khỏe, quyền lợi hợp pháp một cách cần thiết',
        'Trả thù sau khi bị xâm hại',
        'Tự vệ trong mọi trường hợp',
      ],
      correct: 1,
      explanation: 'Điều 22 BLHS 2015: Phòng vệ chính đáng là hành vi của người vì bảo vệ quyền hoặc lợi ích chính đáng mà chống trả lại một cách cần thiết người đang có hành vi xâm phạm.',
    },
    {
      content: 'Tình thế cấp thiết theo BLHS 2015 không phải là tội phạm khi thỏa mãn điều kiện gì?',
      options: [
        'Thiệt hại gây ra nhỏ hơn thiệt hại cần ngăn ngừa',
        'Được cơ quan có thẩm quyền cho phép',
        'Gây thiệt hại cho chính người xâm hại',
        'Không gây thiệt hại cho ai',
      ],
      correct: 0,
      explanation: 'Điều 23 BLHS 2015: Tình thế cấp thiết là tình thế của người vì muốn tránh gây thiệt hại cho quyền, lợi ích hợp pháp mà gây thiệt hại nhỏ hơn thiệt hại cần ngăn ngừa.',
    },
    {
      content: 'Theo Luật Tổ chức Tòa án nhân dân 2014, hệ thống Tòa án nhân dân gồm mấy cấp?',
      options: [
        '2 cấp',
        '3 cấp',
        '4 cấp',
        '5 cấp',
      ],
      correct: 2,
      explanation: 'Hệ thống TAND gồm 4 cấp: TAND tối cao, TAND cấp cao, TAND tỉnh/thành phố trực thuộc trung ương, TAND huyện/quận/thị xã/thành phố thuộc tỉnh.',
    },
    {
      content: 'Viện kiểm sát nhân dân thực hiện chức năng gì theo Hiến pháp 2013?',
      options: [
        'Xét xử',
        'Quản lý hành chính nhà nước',
        'Thực hành quyền công tố và kiểm sát hoạt động tư pháp',
        'Ban hành pháp luật',
      ],
      correct: 2,
      explanation: 'Điều 107 Hiến pháp 2013: "Viện kiểm sát nhân dân thực hành quyền công tố, kiểm sát hoạt động tư pháp."',
    },
    {
      content: 'Công dân có quyền khiếu nại đối với quyết định hành chính trong thời hạn bao lâu kể từ ngày nhận được quyết định?',
      options: [
        '30 ngày',
        '60 ngày',
        '90 ngày',
        '120 ngày',
      ],
      correct: 2,
      explanation: 'Theo Luật Khiếu nại 2011, thời hiệu khiếu nại là 90 ngày kể từ ngày nhận được quyết định hành chính hoặc biết được hành vi hành chính.',
    },
    {
      content: 'Theo Luật Doanh nghiệp 2020, Công ty TNHH hai thành viên trở lên có tối đa bao nhiêu thành viên?',
      options: [
        '30 thành viên',
        '50 thành viên',
        '100 thành viên',
        'Không giới hạn',
      ],
      correct: 1,
      explanation: 'Điều 46 Luật DN 2020: Công ty TNHH hai thành viên trở lên có từ 02 đến 50 thành viên là tổ chức, cá nhân.',
    },
    {
      content: 'Công ty cổ phần có thể phát hành loại chứng khoán nào để huy động vốn?',
      options: [
        'Chỉ cổ phiếu',
        'Chỉ trái phiếu',
        'Cổ phiếu và trái phiếu',
        'Chỉ cổ phiếu ưu đãi',
      ],
      correct: 2,
      explanation: 'Công ty cổ phần có quyền phát hành cổ phiếu (các loại) và trái phiếu để huy động vốn (Điều 111, 128 Luật DN 2020).',
    },
    {
      content: 'Theo Luật Đầu tư 2020, ngành nghề nào sau đây bị CẤM đầu tư kinh doanh?',
      options: [
        'Kinh doanh bất động sản',
        'Kinh doanh dịch vụ đòi nợ',
        'Kinh doanh vận tải',
        'Kinh doanh bảo hiểm',
      ],
      correct: 1,
      explanation: 'Điều 6 Luật Đầu tư 2020 liệt kê ngành nghề cấm, bao gồm kinh doanh dịch vụ đòi nợ (bổ sung từ 2021).',
    },
    {
      content: 'Điều ước quốc tế mà Việt Nam là thành viên có hiệu lực pháp lý như thế nào trong hệ thống pháp luật Việt Nam?',
      options: [
        'Luôn có giá trị cao hơn luật trong nước',
        'Có giá trị thấp hơn Hiến pháp nhưng có thể cao hơn luật khi có quy định khác',
        'Không có giá trị pháp lý tại Việt Nam',
        'Chỉ có giá trị tham khảo',
      ],
      correct: 1,
      explanation: 'Điều ước quốc tế mà Việt Nam là thành viên phải phù hợp với Hiến pháp; khi có xung đột với luật trong nước, ưu tiên áp dụng điều ước quốc tế (trừ Hiến pháp) theo Luật Điều ước quốc tế 2016.',
    },
    {
      content: 'Án lệ được chính thức thừa nhận là nguồn của pháp luật Việt Nam từ năm nào?',
      options: [
        '2005',
        '2010',
        '2015',
        '2019',
      ],
      correct: 2,
      explanation: 'Nghị quyết 04/2019/NQ-HĐTP (thay thế NQ 03/2015) quy định về quy trình lựa chọn, công bố và áp dụng án lệ. Án lệ được chính thức thừa nhận từ 2015.',
    },
    {
      content: 'Theo Luật Hôn nhân và Gia đình 2014, độ tuổi kết hôn tối thiểu là bao nhiêu?',
      options: [
        'Nam 18 tuổi, nữ 16 tuổi',
        'Nam 20 tuổi, nữ 18 tuổi',
        'Nam và nữ đều 18 tuổi',
        'Nam 21 tuổi, nữ 18 tuổi',
      ],
      correct: 1,
      explanation: 'Điều 8 Luật HN&GĐ 2014: Nam từ đủ 20 tuổi trở lên, nữ từ đủ 18 tuổi trở lên mới được kết hôn.',
    },
    {
      content: 'Quyền bất khả xâm phạm về thân thể được quy định tại điều nào của Hiến pháp 2013?',
      options: [
        'Điều 19',
        'Điều 20',
        'Điều 21',
        'Điều 22',
      ],
      correct: 1,
      explanation: 'Điều 20 Hiến pháp 2013: "Mọi người có quyền bất khả xâm phạm về thân thể, được pháp luật bảo hộ về sức khỏe, danh dự và nhân phẩm."',
    },
    {
      content: 'Theo Hiến pháp 2013, quyền nào sau đây là quyền cơ bản của công dân?',
      options: [
        'Quyền biểu tình',
        'Quyền mang vũ khí',
        'Quyền ly khai',
        'Quyền tuyệt đối về tài sản',
      ],
      correct: 0,
      explanation: 'Điều 25 Hiến pháp 2013 ghi nhận công dân có quyền tự do ngôn luận, tự do báo chí, tiếp cận thông tin, hội họp, lập hội, biểu tình theo quy định của pháp luật.',
    },
    {
      content: 'Thời hiệu truy cứu trách nhiệm hình sự đối với tội phạm rất nghiêm trọng là bao nhiêu năm?',
      options: [
        '5 năm',
        '10 năm',
        '15 năm',
        '20 năm',
      ],
      correct: 2,
      explanation: 'Điều 27 BLHS 2015: Thời hiệu truy cứu TNHS: tội ít nghiêm trọng (5 năm), nghiêm trọng (10 năm), rất nghiêm trọng (15 năm), đặc biệt nghiêm trọng (20 năm).',
    },
    {
      content: 'Người bào chữa trong tố tụng hình sự có thể là ai?',
      options: [
        'Chỉ luật sư',
        'Luật sư, người đại diện hợp pháp, bào chữa viên nhân dân, trợ giúp viên pháp lý',
        'Chỉ luật sư và người đại diện hợp pháp',
        'Bất kỳ ai có năng lực hành vi dân sự',
      ],
      correct: 1,
      explanation: 'Điều 72 BLTTHS 2015: Người bào chữa gồm luật sư, người đại diện hợp pháp của người bị buộc tội, bào chữa viên nhân dân, trợ giúp viên pháp lý.',
    },
    {
      content: 'Theo Nghị định 15/2020/NĐ-CP về xử phạt vi phạm hành chính trong lĩnh vực bưu chính, viễn thông, công nghệ thông tin, hành vi đưa thông tin sai sự thật lên mạng xã hội bị phạt tiền tối đa bao nhiêu?',
      options: [
        '10 triệu đồng',
        '20 triệu đồng',
        '30 triệu đồng',
        '50 triệu đồng',
      ],
      correct: 1,
      explanation: 'Nghị định 15/2020/NĐ-CP (sửa đổi bởi NĐ 14/2022): phạt tiền từ 10-20 triệu đồng đối với hành vi cung cấp, chia sẻ thông tin giả mạo, sai sự thật trên mạng xã hội.',
    },
    {
      content: 'Theo Luật Giao dịch điện tử 2023, thông điệp dữ liệu có giá trị như văn bản khi đáp ứng điều kiện nào?',
      options: [
        'Khi được in ra giấy',
        'Khi nội dung có thể truy cập và sử dụng được để tham chiếu',
        'Khi có chữ ký tay',
        'Khi được gửi qua email',
      ],
      correct: 1,
      explanation: 'Thông điệp dữ liệu có giá trị như văn bản khi thông tin chứa trong đó có thể truy cập và sử dụng được để tham chiếu khi cần thiết.',
    },
    {
      content: 'Luật Bảo vệ quyền lợi người tiêu dùng 2023 quy định thời hạn giải quyết khiếu nại của người tiêu dùng đối với tổ chức, cá nhân kinh doanh là bao nhiêu ngày?',
      options: [
        '5 ngày làm việc',
        '7 ngày làm việc',
        '10 ngày làm việc',
        '15 ngày làm việc',
      ],
      correct: 1,
      explanation: 'Theo Luật Bảo vệ quyền lợi NTD 2023, tổ chức/cá nhân kinh doanh phải tiếp nhận và giải quyết khiếu nại trong thời hạn 07 ngày làm việc kể từ ngày nhận được khiếu nại.',
    },
    {
      content: 'Theo Bộ luật Dân sự 2015, hợp đồng vay tài sản có lãi suất tối đa không vượt quá bao nhiêu phần trăm/năm?',
      options: [
        '10%/năm',
        '15%/năm',
        '20%/năm',
        '30%/năm',
      ],
      correct: 2,
      explanation: 'Điều 468 BLDS 2015: Lãi suất theo thỏa thuận không được vượt quá 20%/năm của khoản tiền vay, trừ trường hợp luật khác có liên quan quy định khác.',
    },
    {
      content: 'Theo BLDS 2015, đại diện theo pháp luật của người chưa thành niên là ai?',
      options: [
        'Ông bà nội',
        'Cha, mẹ',
        'Anh, chị cả',
        'Người giám hộ do tòa án chỉ định',
      ],
      correct: 1,
      explanation: 'Điều 136 BLDS 2015: Cha, mẹ là người đại diện theo pháp luật của con chưa thành niên (trừ trường hợp con có người giám hộ riêng theo quy định).',
    },
    {
      content: 'Theo Luật Cạnh tranh 2018, hành vi nào sau đây là hành vi cạnh tranh không lành mạnh?',
      options: [
        'Giảm giá sản phẩm',
        'Quảng cáo so sánh trực tiếp',
        'Xâm phạm bí mật kinh doanh',
        'Mở chi nhánh mới',
      ],
      correct: 2,
      explanation: 'Điều 45 Luật Cạnh tranh 2018 liệt kê các hành vi cạnh tranh không lành mạnh, bao gồm xâm phạm bí mật kinh doanh, ép buộc khách hàng, gây rối hoạt động kinh doanh.',
    },
    {
      content: 'Phương pháp điều chỉnh của ngành luật hành chính có đặc trưng gì?',
      options: [
        'Bình đẳng giữa các bên',
        'Quyền uy - phục tùng (mệnh lệnh - phục tùng)',
        'Tự do thỏa thuận',
        'Hòa giải',
      ],
      correct: 1,
      explanation: 'Luật hành chính sử dụng phương pháp mệnh lệnh - phục tùng (quyền uy - phục tùng), phản ánh quan hệ bất bình đẳng giữa cơ quan nhà nước và đối tượng quản lý.',
    },
    {
      content: 'Phương pháp điều chỉnh đặc trưng của ngành luật dân sự là gì?',
      options: [
        'Mệnh lệnh - phục tùng',
        'Bình đẳng, thỏa thuận, tự định đoạt',
        'Quyền lực nhà nước',
        'Hành chính - mệnh lệnh',
      ],
      correct: 1,
      explanation: 'Luật dân sự sử dụng phương pháp bình đẳng, thỏa thuận, tự định đoạt giữa các chủ thể. Các bên có quyền tự do ý chí trong việc xác lập, thay đổi, chấm dứt quan hệ dân sự.',
    },
    {
      content: 'Biện pháp bảo đảm thực hiện nghĩa vụ nào sau đây KHÔNG được quy định trong BLDS 2015?',
      options: [
        'Cầm cố tài sản',
        'Thế chấp tài sản',
        'Bảo lưu quyền sở hữu',
        'Phong tỏa tài khoản',
      ],
      correct: 3,
      explanation: 'BLDS 2015 quy định 9 biện pháp bảo đảm: cầm cố, thế chấp, đặt cọc, ký cược, ký quỹ, bảo lưu quyền sở hữu, bảo lãnh, tín chấp, cầm giữ tài sản. Phong tỏa tài khoản là biện pháp khẩn cấp tạm thời trong tố tụng.',
    },
    {
      content: 'Kiểu nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam thuộc kiểu nhà nước nào?',
      options: [
        'Nhà nước chủ nô',
        'Nhà nước phong kiến',
        'Nhà nước tư sản',
        'Nhà nước xã hội chủ nghĩa',
      ],
      correct: 3,
      explanation: 'Nhà nước CHXHCN Việt Nam thuộc kiểu nhà nước xã hội chủ nghĩa - kiểu nhà nước cuối cùng trong lịch sử, dựa trên nền tảng kinh tế là chế độ công hữu về tư liệu sản xuất chủ yếu.',
    },
  ] as MCQ[],
  essays: [
    {
      content: 'Phân tích khái niệm, bản chất và vai trò của pháp luật trong đời sống xã hội. Tại sao nói pháp luật vừa mang tính giai cấp vừa mang tính xã hội?',
      points: 4,
      explanation: 'Cần trình bày: khái niệm pháp luật (hệ thống quy tắc xử sự do nhà nước ban hành); bản chất giai cấp (thể hiện ý chí giai cấp thống trị); tính xã hội (điều chỉnh quan hệ xã hội chung, bảo vệ trật tự); mối quan hệ biện chứng giữa hai tính chất.',
    },
    {
      content: 'Trình bày cấu trúc của hệ thống pháp luật Việt Nam (ngành luật, chế định pháp luật, quy phạm pháp luật). Phân tích mối quan hệ giữa các bộ phận cấu thành hệ thống pháp luật.',
      points: 3,
      explanation: 'Cần trình bày 3 cấp độ: ngành luật (công pháp, tư pháp; các ngành luật cụ thể); chế định pháp luật (nhóm QPPL điều chỉnh nhóm QHXH cùng loại); QPPL (đơn vị cơ bản). Mối quan hệ: thống nhất, phụ thuộc, bổ sung.',
    },
    {
      content: 'Phân tích các nguyên tắc cơ bản của Bộ luật Lao động 2019. So sánh quyền đơn phương chấm dứt hợp đồng lao động của người lao động và người sử dụng lao động.',
      points: 4,
      explanation: 'Nguyên tắc: tự do lao động, bảo vệ NLĐ, bình đẳng, tự do thỏa thuận. So sánh đơn phương chấm dứt: NLĐ (Điều 35 - chỉ cần báo trước, không cần lý do); NSDLĐ (Điều 36 - phải có căn cứ luật định, báo trước dài hơn, nhiều ràng buộc).',
    },
    {
      content: 'Trình bày hệ thống hình phạt trong Bộ luật Hình sự 2015. Phân tích nguyên tắc "mọi người đều bình đẳng trước pháp luật" trong lĩnh vực hình sự và mối quan hệ với nguyên tắc suy đoán vô tội.',
      points: 5,
      explanation: 'Hình phạt chính (7 loại) và hình phạt bổ sung (7 loại). Nguyên tắc bình đẳng: không phân biệt dân tộc, giới tính, tôn giáo, địa vị xã hội. Suy đoán vô tội (Điều 13 BLTTHS): chưa có bản án có hiệu lực thì được coi là chưa có tội.',
    },
    {
      content: 'Phân tích cơ chế bảo vệ quyền con người theo Hiến pháp 2013. So sánh cách tiếp cận quyền con người trong Hiến pháp 2013 với Hiến pháp 1992 (sửa đổi 2001).',
      points: 4,
      explanation: 'HP 2013: Chương II đặt trước chương về bộ máy nhà nước; phân biệt quyền con người/quyền công dân; quy định rõ giới hạn quyền (Điều 14 khoản 2). So với HP 1992: vị trí ưu tiên hơn, mở rộng chủ thể, bổ sung nhiều quyền mới, nguyên tắc hạn chế rõ ràng.',
    },
    {
      content: 'Trình bày khái niệm và phân loại vi phạm pháp luật. Phân tích cấu thành vi phạm pháp luật và ý nghĩa của việc xác định cấu thành trong thực tiễn xử lý vi phạm.',
      points: 3,
      explanation: 'Phân loại: 4 loại (hình sự, hành chính, dân sự, kỷ luật). Cấu thành: mặt khách quan (hành vi, hậu quả, mối quan hệ nhân quả), mặt chủ quan (lỗi, động cơ, mục đích), chủ thể, khách thể. Ý nghĩa: xác định đúng loại VPPL, áp dụng đúng chế tài.',
    },
    {
      content: 'Phân tích quy định pháp luật Việt Nam về bảo hộ quyền tác giả trong môi trường số. Những thách thức nào đặt ra đối với việc thực thi quyền sở hữu trí tuệ trên Internet?',
      points: 4,
      explanation: 'Quy định: Luật SHTT (chương quyền tác giả), NĐ 17/2023, Luật GDĐT, Luật ANM. Thách thức: sao chép dễ dàng, xác định chủ thể vi phạm khó, xuyên biên giới, công nghệ AI tạo nội dung, nền tảng trung gian, cân bằng quyền tiếp cận và bảo hộ.',
    },
    {
      content: 'Phân tích mối quan hệ giữa Luật An ninh mạng 2018 và quyền tự do ngôn luận, quyền riêng tư của công dân theo Hiến pháp 2013. Đề xuất giải pháp cân bằng giữa an ninh quốc gia và quyền tự do cá nhân.',
      points: 5,
      explanation: 'Phân tích: quyền tự do ngôn luận (Điều 25 HP) vs nghĩa vụ an ninh mạng; quyền riêng tư (Điều 21 HP) vs yêu cầu lưu trữ/cung cấp dữ liệu; nguyên tắc hạn chế quyền (Điều 14 khoản 2). Giải pháp: minh bạch, tỷ lệ, giám sát độc lập, bảo vệ dữ liệu.',
    },
    {
      content: 'So sánh Công ty TNHH và Công ty cổ phần theo Luật Doanh nghiệp 2020 về các tiêu chí: cơ cấu thành viên/cổ đông, vốn, quyền chuyển nhượng, cơ cấu tổ chức quản lý, huy động vốn. Tư vấn lựa chọn loại hình phù hợp cho startup công nghệ.',
      points: 4,
      explanation: 'So sánh: TNHH (2-50 thành viên, vốn góp, hạn chế chuyển nhượng, HĐTV/CT) vs CTCP (từ 3 cổ đông, cổ phần, tự do chuyển nhượng, ĐHĐCĐ/HĐQT, phát hành CK). Startup nên chọn CTCP: linh hoạt huy động vốn, thu hút nhà đầu tư, ESOP dễ triển khai.',
    },
    {
      content: 'Phân tích giá trị pháp lý của hợp đồng điện tử trong thương mại điện tử xuyên biên giới. Trình bày các vấn đề pháp lý phát sinh và hướng giải quyết theo pháp luật Việt Nam và điều ước quốc tế.',
      points: 5,
      explanation: 'Giá trị pháp lý: Luật GDĐT 2023, Công ước Liên Hợp Quốc về HĐĐT 2005, Luật Mẫu UNCITRAL. Vấn đề: xác định luật áp dụng, thẩm quyền tòa án, chữ ký điện tử xuyên biên giới, bảo vệ NTD, thuế TMĐT. Giải quyết: áp dụng tư pháp quốc tế, điều khoản lựa chọn luật, cơ chế ODR.',
    },
  ] as Essay[],
};
