type MCQ = { content: string; options: string[]; correct: number; explanation?: string };
type Essay = { content: string; explanation?: string; points?: number };

// ─── Đề 1: Lập trình mạng ──────────────────────────────────────────────────
export const netQ1: { mcqs: MCQ[]; essays: Essay[] } = {
  mcqs: [
    {
      content: "Mô hình OSI có bao nhiêu tầng?",
      options: ["5 tầng", "6 tầng", "7 tầng", "4 tầng"],
      correct: 2,
      explanation: "Mô hình OSI gồm 7 tầng: Physical, Data Link, Network, Transport, Session, Presentation, Application.",
    },
    {
      content: "Giao thức TCP hoạt động ở tầng nào trong mô hình OSI?",
      options: ["Tầng mạng (Network)", "Tầng giao vận (Transport)", "Tầng ứng dụng (Application)", "Tầng phiên (Session)"],
      correct: 1,
      explanation: "TCP là giao thức tầng giao vận (Transport layer), chịu trách nhiệm truyền dữ liệu tin cậy giữa hai đầu.",
    },
    {
      content: "Trong lập trình socket, hàm bind() dùng để làm gì?",
      options: [
        "Kết nối đến server",
        "Gán địa chỉ IP và port cho socket",
        "Lắng nghe kết nối đến",
        "Gửi dữ liệu qua socket",
      ],
      correct: 1,
      explanation: "bind() gán một địa chỉ cục bộ (IP + port) cho socket để các client có thể kết nối đến.",
    },
    {
      content: "Cổng mặc định của giao thức HTTP là bao nhiêu?",
      options: ["21", "443", "80", "8080"],
      correct: 2,
      explanation: "HTTP sử dụng cổng 80 theo mặc định. HTTPS sử dụng cổng 443.",
    },
    {
      content: "Giao thức UDP có đặc điểm nào sau đây?",
      options: [
        "Đảm bảo thứ tự gói tin",
        "Không đảm bảo độ tin cậy, không kết nối",
        "Thiết lập kết nối trước khi truyền",
        "Có cơ chế kiểm soát luồng (flow control)",
      ],
      correct: 1,
      explanation: "UDP là giao thức không kết nối (connectionless), không đảm bảo tin cậy, thứ tự hay kiểm soát luồng.",
    },
    {
      content: "Quá trình bắt tay ba bước (three-way handshake) của TCP bao gồm các bước nào?",
      options: [
        "SYN → ACK → FIN",
        "SYN → SYN-ACK → ACK",
        "ACK → SYN → FIN",
        "FIN → ACK → RST",
      ],
      correct: 1,
      explanation: "Three-way handshake: Client gửi SYN, Server trả SYN-ACK, Client gửi ACK để thiết lập kết nối.",
    },
    {
      content: "Trong Java, lớp nào được sử dụng để tạo socket phía server?",
      options: ["Socket", "ServerSocket", "DatagramSocket", "SocketChannel"],
      correct: 1,
      explanation: "ServerSocket dùng để tạo server socket lắng nghe kết nối TCP từ client.",
    },
    {
      content: "DNS viết tắt của cụm từ nào?",
      options: [
        "Dynamic Network Service",
        "Domain Name System",
        "Data Network Standard",
        "Digital Naming Service",
      ],
      correct: 1,
      explanation: "DNS (Domain Name System) là hệ thống phân giải tên miền thành địa chỉ IP.",
    },
    {
      content: "Phương thức HTTP nào dùng để lấy dữ liệu từ server mà không thay đổi trạng thái?",
      options: ["POST", "PUT", "GET", "DELETE"],
      correct: 2,
      explanation: "GET là phương thức idempotent dùng để truy xuất tài nguyên mà không làm thay đổi trạng thái server.",
    },
    {
      content: "Trong mô hình Client-Server, vai trò của server là gì?",
      options: [
        "Gửi yêu cầu đến client",
        "Lắng nghe và xử lý yêu cầu từ client",
        "Chỉ lưu trữ dữ liệu cục bộ",
        "Tạo giao diện người dùng",
      ],
      correct: 1,
      explanation: "Server lắng nghe kết nối, nhận yêu cầu từ client, xử lý và trả về kết quả.",
    },
    {
      content: "Serialization trong lập trình mạng là gì?",
      options: [
        "Mã hóa dữ liệu bằng thuật toán RSA",
        "Chuyển đổi đối tượng thành chuỗi byte để truyền qua mạng",
        "Nén dữ liệu trước khi gửi",
        "Phân mảnh gói tin thành các segment",
      ],
      correct: 1,
      explanation: "Serialization chuyển đổi object thành dạng byte stream để có thể truyền qua mạng hoặc lưu trữ.",
    },
    {
      content: "WebSocket khác HTTP ở điểm nào?",
      options: [
        "WebSocket chỉ hỗ trợ truyền văn bản",
        "WebSocket là giao thức truyền thông hai chiều, full-duplex",
        "WebSocket không cần thiết lập kết nối",
        "WebSocket hoạt động ở tầng mạng",
      ],
      correct: 1,
      explanation: "WebSocket cung cấp kênh truyền thông full-duplex trên một kết nối TCP duy nhất, khác với HTTP request-response.",
    },
    {
      content: "SSL/TLS được sử dụng chủ yếu để làm gì?",
      options: [
        "Tăng tốc độ truyền dữ liệu",
        "Nén dữ liệu truyền qua mạng",
        "Mã hóa và bảo mật dữ liệu truyền giữa client và server",
        "Phân giải tên miền",
      ],
      correct: 2,
      explanation: "SSL/TLS mã hóa dữ liệu truyền trên mạng, đảm bảo tính bí mật, toàn vẹn và xác thực.",
    },
    {
      content: "Trong REST API, mã trạng thái HTTP 404 có ý nghĩa gì?",
      options: [
        "Yêu cầu thành công",
        "Lỗi server nội bộ",
        "Không tìm thấy tài nguyên",
        "Không có quyền truy cập",
      ],
      correct: 2,
      explanation: "HTTP 404 Not Found cho biết server không tìm thấy tài nguyên được yêu cầu.",
    },
    {
      content: "Đa luồng (multithreading) trong server mạng giúp gì?",
      options: [
        "Giảm băng thông sử dụng",
        "Xử lý đồng thời nhiều kết nối client",
        "Tăng kích thước gói tin",
        "Tự động mã hóa dữ liệu",
      ],
      correct: 1,
      explanation: "Multithreading cho phép server tạo thread riêng cho mỗi client, xử lý song song nhiều kết nối.",
    },
    {
      content: "Hàm listen() trong socket programming có tác dụng gì?",
      options: [
        "Gửi dữ liệu đến client",
        "Đặt socket ở trạng thái lắng nghe kết nối đến",
        "Nhận dữ liệu từ client",
        "Đóng kết nối socket",
      ],
      correct: 1,
      explanation: "listen() chuyển socket sang trạng thái passive, sẵn sàng chấp nhận kết nối đến từ client.",
    },
    {
      content: "Giao thức nào sử dụng cổng 443?",
      options: ["HTTP", "FTP", "HTTPS", "SMTP"],
      correct: 2,
      explanation: "HTTPS (HTTP Secure) sử dụng cổng 443, là phiên bản bảo mật của HTTP với SSL/TLS.",
    },
    {
      content: "RPC (Remote Procedure Call) là gì?",
      options: [
        "Giao thức truyền file",
        "Cơ chế cho phép gọi hàm trên máy từ xa như gọi hàm cục bộ",
        "Thuật toán mã hóa dữ liệu",
        "Giao thức định tuyến mạng",
      ],
      correct: 1,
      explanation: "RPC cho phép chương trình gọi thủ tục/hàm trên máy tính khác trong mạng một cách trong suốt.",
    },
    {
      content: "Trong C#, lớp TcpClient dùng để làm gì?",
      options: [
        "Tạo server UDP",
        "Kết nối TCP đến server từ phía client",
        "Phân giải DNS",
        "Mã hóa dữ liệu SSL",
      ],
      correct: 1,
      explanation: "TcpClient cung cấp kết nối TCP ở phía client, cho phép gửi/nhận dữ liệu qua stream.",
    },
    {
      content: "Địa chỉ IP loopback (localhost) là địa chỉ nào?",
      options: ["192.168.1.1", "10.0.0.1", "127.0.0.1", "255.255.255.0"],
      correct: 2,
      explanation: "127.0.0.1 là địa chỉ loopback, trỏ về chính máy tính đang chạy (localhost).",
    },
    {
      content: "Giao thức SMTP dùng để làm gì?",
      options: [
        "Truyền file giữa các máy",
        "Gửi email",
        "Duyệt web",
        "Phân giải tên miền",
      ],
      correct: 1,
      explanation: "SMTP (Simple Mail Transfer Protocol) là giao thức chuẩn để gửi email qua Internet.",
    },
    {
      content: "Trong lập trình socket TCP, thứ tự các hàm phía server thường là?",
      options: [
        "socket → connect → send → close",
        "socket → bind → listen → accept",
        "socket → listen → bind → accept",
        "socket → accept → bind → listen",
      ],
      correct: 1,
      explanation: "Server TCP: tạo socket, bind địa chỉ, listen lắng nghe, accept chấp nhận kết nối.",
    },
    {
      content: "JSON là gì trong ngữ cảnh truyền dữ liệu mạng?",
      options: [
        "Một giao thức mạng tầng giao vận",
        "Định dạng trao đổi dữ liệu nhẹ, dễ đọc",
        "Thuật toán nén dữ liệu",
        "Phương thức mã hóa đối xứng",
      ],
      correct: 1,
      explanation: "JSON (JavaScript Object Notation) là định dạng dữ liệu text-based, nhẹ, dễ đọc, phổ biến trong API.",
    },
    {
      content: "Mô hình TCP/IP có bao nhiêu tầng?",
      options: ["7 tầng", "5 tầng", "4 tầng", "3 tầng"],
      correct: 2,
      explanation: "Mô hình TCP/IP có 4 tầng: Network Access, Internet, Transport, Application.",
    },
    {
      content: "Giao thức FTP sử dụng cổng nào làm cổng điều khiển?",
      options: ["80", "21", "25", "110"],
      correct: 1,
      explanation: "FTP sử dụng cổng 21 cho kênh điều khiển (control) và cổng 20 cho kênh dữ liệu (data).",
    },
    {
      content: "Blocking I/O trong lập trình socket có nghĩa là gì?",
      options: [
        "Socket tự động đóng sau mỗi lần gửi",
        "Luồng thực thi bị tạm dừng cho đến khi thao tác I/O hoàn thành",
        "Dữ liệu bị chặn bởi firewall",
        "Server từ chối kết nối từ client",
      ],
      correct: 1,
      explanation: "Blocking I/O khiến thread bị chặn (block) đến khi phép đọc/ghi hoàn tất, không thực thi tiếp được.",
    },
    {
      content: "Non-blocking I/O khác blocking I/O ở điểm nào?",
      options: [
        "Non-blocking I/O mã hóa dữ liệu tự động",
        "Non-blocking I/O trả về ngay lập tức dù thao tác chưa hoàn thành",
        "Non-blocking I/O chỉ hoạt động với UDP",
        "Non-blocking I/O không cần socket",
      ],
      correct: 1,
      explanation: "Non-blocking I/O không chặn thread, trả kết quả ngay (có thể chưa có data), cho phép xử lý nhiều kết nối.",
    },
    {
      content: "Mã trạng thái HTTP 500 biểu thị điều gì?",
      options: [
        "Yêu cầu thành công",
        "Chuyển hướng tạm thời",
        "Lỗi nội bộ server",
        "Yêu cầu bị từ chối do xác thực",
      ],
      correct: 2,
      explanation: "HTTP 500 Internal Server Error cho biết server gặp lỗi không xác định khi xử lý yêu cầu.",
    },
    {
      content: "Trong Java, lớp DatagramSocket dùng cho giao thức nào?",
      options: ["TCP", "HTTP", "UDP", "FTP"],
      correct: 2,
      explanation: "DatagramSocket dùng để gửi và nhận DatagramPacket qua giao thức UDP (không kết nối).",
    },
    {
      content: "Phương thức HTTP POST khác GET ở điểm nào?",
      options: [
        "POST gửi dữ liệu trong body, GET gửi qua URL",
        "POST chỉ dùng cho HTTPS, GET cho HTTP",
        "POST nhanh hơn GET",
        "GET có thể gửi file, POST thì không",
      ],
      correct: 0,
      explanation: "POST gửi dữ liệu trong request body, phù hợp cho dữ liệu lớn. GET gửi qua query string trên URL.",
    },
    {
      content: "Multicast trong mạng là gì?",
      options: [
        "Gửi dữ liệu đến tất cả các máy trong mạng",
        "Gửi dữ liệu đến một nhóm máy cụ thể",
        "Gửi dữ liệu đến đúng một máy",
        "Chặn dữ liệu từ một nhóm máy",
      ],
      correct: 1,
      explanation: "Multicast gửi dữ liệu đến một nhóm (group) các máy đã đăng ký, hiệu quả hơn broadcast.",
    },
    {
      content: "Port number có phạm vi giá trị nào?",
      options: ["0 - 1023", "0 - 65535", "1 - 49151", "1024 - 65535"],
      correct: 1,
      explanation: "Port number có giá trị từ 0 đến 65535 (16-bit). Trong đó 0-1023 là well-known ports.",
    },
    {
      content: "Giao thức nào trong TCP/IP tương ứng tầng Internet?",
      options: ["TCP", "UDP", "IP", "HTTP"],
      correct: 2,
      explanation: "IP (Internet Protocol) hoạt động ở tầng Internet, chịu trách nhiệm định tuyến gói tin.",
    },
    {
      content: "Thread pool trong server đa luồng có lợi ích gì?",
      options: [
        "Tạo thread không giới hạn cho mỗi client",
        "Tái sử dụng thread, giảm chi phí tạo/hủy thread",
        "Tự động mã hóa dữ liệu truyền",
        "Tăng kích thước buffer nhận dữ liệu",
      ],
      correct: 1,
      explanation: "Thread pool tạo sẵn một nhóm thread, tái sử dụng chúng cho các kết nối, tránh overhead tạo/hủy liên tục.",
    },
    {
      content: "RESTful API tuân theo nguyên tắc nào?",
      options: [
        "Stateful - server lưu trạng thái client",
        "Stateless - mỗi request chứa đủ thông tin cần thiết",
        "Chỉ hỗ trợ định dạng XML",
        "Bắt buộc sử dụng WebSocket",
      ],
      correct: 1,
      explanation: "REST yêu cầu stateless: mỗi request từ client phải chứa đầy đủ thông tin, server không lưu session.",
    },
    {
      content: "Trong C#, namespace nào chứa các lớp lập trình mạng cơ bản?",
      options: [
        "System.IO",
        "System.Net.Sockets",
        "System.Threading",
        "System.Collections",
      ],
      correct: 1,
      explanation: "System.Net.Sockets chứa TcpClient, TcpListener, UdpClient, Socket và các lớp mạng cơ bản.",
    },
    {
      content: "HTTP/2 cải tiến gì so với HTTP/1.1?",
      options: [
        "Sử dụng UDP thay vì TCP",
        "Hỗ trợ multiplexing nhiều request trên một kết nối",
        "Loại bỏ hoàn toàn header",
        "Chỉ hỗ trợ phương thức GET",
      ],
      correct: 1,
      explanation: "HTTP/2 hỗ trợ multiplexing, header compression, server push trên một kết nối TCP duy nhất.",
    },
    {
      content: "Broadcast trong mạng nghĩa là gì?",
      options: [
        "Gửi dữ liệu đến một máy duy nhất",
        "Gửi dữ liệu đến một nhóm máy",
        "Gửi dữ liệu đến tất cả máy trong mạng",
        "Từ chối nhận dữ liệu từ mạng",
      ],
      correct: 2,
      explanation: "Broadcast gửi gói tin đến tất cả các thiết bị trong cùng mạng (broadcast domain).",
    },
    {
      content: "Lỗi 'Connection refused' khi kết nối socket thường do nguyên nhân nào?",
      options: [
        "Mạng quá chậm",
        "Server chưa chạy hoặc không lắng nghe trên port đó",
        "Client gửi quá nhiều dữ liệu",
        "Firewall mã hóa gói tin",
      ],
      correct: 1,
      explanation: "Connection refused xảy ra khi không có tiến trình nào lắng nghe trên IP:port mà client kết nối đến.",
    },
    {
      content: "Giao thức ARP dùng để làm gì?",
      options: [
        "Phân giải tên miền thành IP",
        "Phân giải địa chỉ IP thành địa chỉ MAC",
        "Mã hóa gói tin",
        "Định tuyến gói tin giữa các mạng",
      ],
      correct: 1,
      explanation: "ARP (Address Resolution Protocol) ánh xạ địa chỉ IP sang địa chỉ MAC trong mạng LAN.",
    },
  ],

  essays: [
    {
      content: "Trình bày chi tiết quá trình bắt tay ba bước (three-way handshake) trong TCP. Vẽ sơ đồ minh họa và giải thích vai trò của từng bước.",
      explanation: "Cần nêu: SYN (client gửi, chọn ISN), SYN-ACK (server gửi, xác nhận ISN client, chọn ISN server), ACK (client xác nhận ISN server). Mỗi bước có ý nghĩa đồng bộ số thứ tự và thiết lập kết nối hai chiều.",
      points: 3,
    },
    {
      content: "So sánh giao thức TCP và UDP. Cho ví dụ ứng dụng thực tế phù hợp với từng giao thức và giải thích lý do lựa chọn.",
      explanation: "TCP: tin cậy, có kết nối, kiểm soát luồng → web, email, FTP. UDP: nhanh, không kết nối, có thể mất gói → streaming, game online, DNS. Cần phân tích ưu/nhược từng giao thức.",
      points: 3,
    },
    {
      content: "Viết chương trình Java/C# mô tả server TCP đơn giản có thể nhận kết nối từ nhiều client đồng thời sử dụng đa luồng. Giải thích cách hoạt động của chương trình.",
      explanation: "Cần có: ServerSocket/TcpListener, vòng lặp accept(), tạo thread mới cho mỗi client, xử lý I/O trong thread, đóng kết nối. Giải thích luồng xử lý và tại sao cần đa luồng.",
      points: 5,
    },
    {
      content: "Trình bày mô hình Client-Server và mô hình Peer-to-Peer. So sánh ưu nhược điểm và cho ví dụ ứng dụng thực tế.",
      explanation: "Client-Server: tập trung, dễ quản lý, phụ thuộc server (web). P2P: phân tán, không có điểm lỗi đơn, khó quản lý (BitTorrent). Phân tích khả năng mở rộng, bảo mật, chi phí.",
      points: 3,
    },
    {
      content: "Giải thích cơ chế hoạt động của DNS. Mô tả quá trình phân giải tên miền từ khi người dùng nhập URL đến khi nhận được địa chỉ IP.",
      explanation: "Quy trình: kiểm tra cache → hỏi Recursive Resolver → Root DNS → TLD DNS → Authoritative DNS → trả IP. Nêu các loại record (A, AAAA, CNAME, MX) và cơ chế caching.",
      points: 3,
    },
    {
      content: "Thiết kế và triển khai một REST API đơn giản cho hệ thống quản lý sinh viên với các thao tác CRUD. Mô tả các endpoint, phương thức HTTP và mã trạng thái tương ứng.",
      explanation: "GET /students, GET /students/:id, POST /students, PUT /students/:id, DELETE /students/:id. Mô tả request body, response format (JSON), status codes (200, 201, 400, 404, 500).",
      points: 4,
    },
    {
      content: "Trình bày vai trò của SSL/TLS trong bảo mật truyền thông mạng. Mô tả quá trình TLS handshake và các thành phần mật mã được sử dụng.",
      explanation: "TLS handshake: ClientHello → ServerHello + Certificate → Key Exchange → Finished. Các thành phần: mã hóa bất đối xứng (RSA/ECDHE), chứng chỉ số, mã hóa đối xứng (AES), hàm băm (SHA).",
      points: 4,
    },
    {
      content: "So sánh WebSocket với HTTP truyền thống. Trong trường hợp nào nên sử dụng WebSocket thay vì HTTP? Viết đoạn mã minh họa kết nối WebSocket cơ bản.",
      explanation: "HTTP: request-response, half-duplex. WebSocket: full-duplex, persistent. WebSocket phù hợp cho: chat, game, live notification, real-time dashboard. Mã minh họa kết nối và gửi/nhận message.",
      points: 3,
    },
    {
      content: "Giải thích khái niệm Serialization và Deserialization trong lập trình mạng. Tại sao cần serialize dữ liệu trước khi truyền? So sánh JSON và Protocol Buffers.",
      explanation: "Serialize: object → bytes. Deserialize: bytes → object. Cần vì mạng chỉ truyền bytes. JSON: text-based, dễ đọc, lớn hơn. Protobuf: binary, nhỏ gọn, nhanh, cần schema.",
      points: 3,
    },
    {
      content: "Trình bày các mô hình xử lý đồng thời trong server mạng: multi-process, multi-thread, event-driven (I/O multiplexing). Phân tích ưu nhược điểm từng mô hình.",
      explanation: "Multi-process: cách ly tốt, tốn tài nguyên. Multi-thread: nhẹ hơn, chia sẻ bộ nhớ, race condition. Event-driven (select/epoll): hiệu quả cao, phức tạp code. So sánh hiệu năng và trường hợp sử dụng.",
      points: 4,
    },
  ],
};

// ─── Đề 2: Lập trình mạng ──────────────────────────────────────────────────
export const netQ2: { mcqs: MCQ[]; essays: Essay[] } = {
  mcqs: [
    {
      content: "Tầng nào trong mô hình TCP/IP chịu trách nhiệm định tuyến gói tin?",
      options: ["Tầng ứng dụng (Application)", "Tầng giao vận (Transport)", "Tầng Internet", "Tầng truy cập mạng (Network Access)"],
      correct: 2,
      explanation: "Tầng Internet (chứa giao thức IP) chịu trách nhiệm định địa chỉ và định tuyến gói tin giữa các mạng.",
    },
    {
      content: "Hàm accept() trong lập trình socket TCP trả về gì?",
      options: [
        "Địa chỉ IP của client",
        "Một socket mới để giao tiếp với client",
        "Số byte nhận được",
        "Mã lỗi kết nối",
      ],
      correct: 1,
      explanation: "accept() tạo và trả về một socket mới dành riêng cho kết nối với client vừa kết nối đến.",
    },
    {
      content: "Giao thức DHCP dùng để làm gì?",
      options: [
        "Phân giải tên miền",
        "Cấp phát địa chỉ IP tự động cho thiết bị trong mạng",
        "Mã hóa dữ liệu truyền",
        "Truyền file giữa các máy",
      ],
      correct: 1,
      explanation: "DHCP (Dynamic Host Configuration Protocol) tự động cấp IP, subnet mask, gateway cho thiết bị mạng.",
    },
    {
      content: "Mã trạng thái HTTP 201 có ý nghĩa gì?",
      options: [
        "Yêu cầu thành công, tài nguyên đã được tạo",
        "Chuyển hướng vĩnh viễn",
        "Lỗi cú pháp yêu cầu",
        "Server quá tải",
      ],
      correct: 0,
      explanation: "HTTP 201 Created cho biết yêu cầu thành công và server đã tạo tài nguyên mới (thường sau POST).",
    },
    {
      content: "Trong Java, lớp InetAddress dùng để làm gì?",
      options: [
        "Tạo kết nối TCP",
        "Biểu diễn địa chỉ IP và phân giải tên miền",
        "Gửi email",
        "Đọc file từ server",
      ],
      correct: 1,
      explanation: "InetAddress biểu diễn địa chỉ IP (IPv4/IPv6) và cung cấp phương thức phân giải DNS.",
    },
    {
      content: "Phương thức HTTP PUT khác POST ở điểm nào?",
      options: [
        "PUT tạo mới, POST cập nhật",
        "PUT idempotent - cập nhật toàn bộ tài nguyên, POST tạo mới",
        "PUT không có body, POST có body",
        "PUT chỉ dùng cho HTTPS",
      ],
      correct: 1,
      explanation: "PUT là idempotent, thay thế toàn bộ tài nguyên. POST không idempotent, thường dùng tạo mới tài nguyên.",
    },
    {
      content: "Cổng mặc định của giao thức SSH là bao nhiêu?",
      options: ["21", "22", "23", "25"],
      correct: 1,
      explanation: "SSH (Secure Shell) sử dụng cổng 22 để cung cấp kết nối điều khiển từ xa an toàn.",
    },
    {
      content: "Socket là gì trong lập trình mạng?",
      options: [
        "Một thiết bị phần cứng mạng",
        "Điểm cuối (endpoint) giao tiếp giữa hai tiến trình qua mạng",
        "Giao thức tầng ứng dụng",
        "Phần mềm quản lý router",
      ],
      correct: 1,
      explanation: "Socket là endpoint giao tiếp mạng, được xác định bởi cặp (IP, port), cho phép hai tiến trình trao đổi dữ liệu.",
    },
    {
      content: "Trong quá trình đóng kết nối TCP, bước nào xảy ra đầu tiên?",
      options: [
        "Server gửi RST",
        "Client gửi FIN",
        "Server gửi SYN",
        "Client gửi ACK",
      ],
      correct: 1,
      explanation: "Khi đóng kết nối TCP (four-way handshake), bên muốn đóng gửi FIN trước, thông báo ngừng gửi dữ liệu.",
    },
    {
      content: "Buffer overflow trong lập trình mạng có thể dẫn đến hậu quả gì?",
      options: [
        "Tăng tốc độ truyền dữ liệu",
        "Lỗi bảo mật, cho phép thực thi mã độc",
        "Tự động nén dữ liệu",
        "Tăng kích thước gói tin",
      ],
      correct: 1,
      explanation: "Buffer overflow có thể ghi đè bộ nhớ, dẫn đến crash hoặc cho phép attacker chèn và thực thi mã độc.",
    },
    {
      content: "NAT (Network Address Translation) giải quyết vấn đề gì?",
      options: [
        "Mã hóa dữ liệu truyền",
        "Thiếu hụt địa chỉ IPv4 công cộng",
        "Tăng tốc độ DNS",
        "Nén gói tin mạng",
      ],
      correct: 1,
      explanation: "NAT cho phép nhiều thiết bị mạng nội bộ chia sẻ một địa chỉ IP công cộng, giảm nhu cầu IP public.",
    },
    {
      content: "Trong C#, lớp TcpListener dùng để làm gì?",
      options: [
        "Kết nối đến server TCP",
        "Lắng nghe và chấp nhận kết nối TCP từ client",
        "Gửi dữ liệu UDP",
        "Phân giải tên miền",
      ],
      correct: 1,
      explanation: "TcpListener lắng nghe kết nối TCP đến trên một IP:port cụ thể, tương đương ServerSocket trong Java.",
    },
    {
      content: "Giao thức ICMP được sử dụng bởi công cụ nào?",
      options: ["Web browser", "FTP client", "ping và traceroute", "Email client"],
      correct: 2,
      explanation: "ICMP (Internet Control Message Protocol) được sử dụng bởi ping (echo request/reply) và traceroute.",
    },
    {
      content: "Khái niệm 'stateless' trong HTTP có nghĩa là gì?",
      options: [
        "Server không lưu trạng thái giữa các request",
        "Client không gửi header",
        "Mỗi request phải dùng kết nối mới",
        "Server không trả response",
      ],
      correct: 0,
      explanation: "Stateless nghĩa là mỗi HTTP request độc lập, server không giữ thông tin về các request trước đó.",
    },
    {
      content: "Trong lập trình socket, hàm connect() dùng ở phía nào?",
      options: [
        "Chỉ phía server",
        "Chỉ phía client",
        "Cả client và server",
        "Chỉ dùng với UDP",
      ],
      correct: 1,
      explanation: "connect() được gọi ở phía client để thiết lập kết nối TCP đến server.",
    },
    {
      content: "IPv6 sử dụng bao nhiêu bit cho địa chỉ?",
      options: ["32 bit", "64 bit", "128 bit", "256 bit"],
      correct: 2,
      explanation: "IPv6 sử dụng 128 bit (16 byte) cho địa chỉ, cung cấp không gian địa chỉ rất lớn so với 32 bit của IPv4.",
    },
    {
      content: "Middleware trong kiến trúc web server có vai trò gì?",
      options: [
        "Thay thế hoàn toàn server",
        "Xử lý request trung gian trước khi đến handler chính",
        "Tạo kết nối cơ sở dữ liệu trực tiếp từ client",
        "Mã hóa địa chỉ MAC",
      ],
      correct: 1,
      explanation: "Middleware nằm giữa request và handler, thực hiện các tác vụ chung như logging, auth, CORS, parsing body.",
    },
    {
      content: "Wireshark là công cụ dùng để làm gì?",
      options: [
        "Lập trình socket",
        "Bắt và phân tích gói tin mạng",
        "Thiết kế giao diện web",
        "Quản lý cơ sở dữ liệu",
      ],
      correct: 1,
      explanation: "Wireshark là công cụ packet sniffer, cho phép capture và phân tích chi tiết các gói tin trên mạng.",
    },
    {
      content: "Trong REST, resource được định danh bằng gì?",
      options: ["Số port", "URI (Uniform Resource Identifier)", "MAC address", "Session ID"],
      correct: 1,
      explanation: "Trong REST, mỗi tài nguyên được định danh duy nhất bằng URI, ví dụ /api/users/123.",
    },
    {
      content: "Giao thức nào hoạt động ở tầng Application trong TCP/IP?",
      options: ["IP", "TCP", "HTTP", "ARP"],
      correct: 2,
      explanation: "HTTP hoạt động ở tầng Application. IP ở tầng Internet, TCP ở tầng Transport.",
    },
    {
      content: "Keep-Alive trong HTTP/1.1 có tác dụng gì?",
      options: [
        "Tự động reload trang web",
        "Duy trì kết nối TCP cho nhiều request liên tiếp",
        "Gửi heartbeat đến DNS server",
        "Mã hóa cookie phiên",
      ],
      correct: 1,
      explanation: "Keep-Alive giữ kết nối TCP mở để tái sử dụng cho nhiều HTTP request, giảm overhead tạo kết nối mới.",
    },
    {
      content: "Deadlock trong server đa luồng xảy ra khi nào?",
      options: [
        "Server nhận quá nhiều kết nối",
        "Hai hoặc nhiều thread chờ đợi lẫn nhau giải phóng tài nguyên",
        "Client ngắt kết nối đột ngột",
        "Buffer gửi đầy",
      ],
      correct: 1,
      explanation: "Deadlock xảy ra khi các thread giữ tài nguyên và chờ tài nguyên của thread khác, tạo vòng chờ vô hạn.",
    },
    {
      content: "Trong Java, ObjectOutputStream dùng trong lập trình mạng để làm gì?",
      options: [
        "Tạo kết nối TCP",
        "Serialize và gửi object qua stream",
        "Phân giải DNS",
        "Mã hóa SSL",
      ],
      correct: 1,
      explanation: "ObjectOutputStream serialize đối tượng Java thành byte stream, cho phép gửi object qua socket.",
    },
    {
      content: "CORS (Cross-Origin Resource Sharing) giải quyết vấn đề gì?",
      options: [
        "Mã hóa dữ liệu truyền",
        "Cho phép truy cập API từ domain khác một cách an toàn",
        "Nén dữ liệu HTTP",
        "Cân bằng tải giữa các server",
      ],
      correct: 1,
      explanation: "CORS cho phép server chỉ định domain nào được phép truy cập tài nguyên, vượt qua Same-Origin Policy.",
    },
    {
      content: "Subnet mask 255.255.255.0 tương đương với ký hiệu CIDR nào?",
      options: ["/8", "/16", "/24", "/32"],
      correct: 2,
      explanation: "255.255.255.0 có 24 bit 1 liên tiếp, tương đương /24 trong ký hiệu CIDR.",
    },
    {
      content: "Giao thức gRPC sử dụng định dạng nào để serialize dữ liệu?",
      options: ["JSON", "XML", "Protocol Buffers", "YAML"],
      correct: 2,
      explanation: "gRPC mặc định dùng Protocol Buffers (protobuf) - định dạng binary nhỏ gọn và nhanh hơn JSON/XML.",
    },
    {
      content: "Trong lập trình mạng, timeout socket dùng để làm gì?",
      options: [
        "Tăng tốc độ truyền dữ liệu",
        "Giới hạn thời gian chờ cho thao tác socket",
        "Mã hóa kết nối",
        "Tự động kết nối lại khi mất mạng",
      ],
      correct: 1,
      explanation: "Socket timeout giới hạn thời gian chờ cho connect/read/write, tránh thread bị block vô thời hạn.",
    },
    {
      content: "Load Balancer trong hệ thống mạng có chức năng gì?",
      options: [
        "Mã hóa tất cả dữ liệu truyền",
        "Phân phối request đều giữa nhiều server",
        "Lưu cache tất cả response",
        "Phân giải tên miền nhanh hơn",
      ],
      correct: 1,
      explanation: "Load Balancer phân phối traffic đến nhiều server backend, tăng khả năng chịu tải và tính sẵn sàng.",
    },
    {
      content: "Phương thức HTTP DELETE dùng để làm gì?",
      options: [
        "Xóa tài nguyên trên server",
        "Xóa cache trên client",
        "Xóa cookie",
        "Ngắt kết nối TCP",
      ],
      correct: 0,
      explanation: "HTTP DELETE yêu cầu server xóa tài nguyên được chỉ định bởi URI.",
    },
    {
      content: "Trong mô hình OSI, tầng nào chịu trách nhiệm mã hóa dữ liệu?",
      options: [
        "Tầng phiên (Session)",
        "Tầng trình diễn (Presentation)",
        "Tầng ứng dụng (Application)",
        "Tầng giao vận (Transport)",
      ],
      correct: 1,
      explanation: "Tầng Presentation chịu trách nhiệm mã hóa, giải mã, nén dữ liệu và chuyển đổi định dạng.",
    },
    {
      content: "Race condition trong server đa luồng là gì?",
      options: [
        "Server xử lý request quá nhanh",
        "Nhiều thread truy cập tài nguyên chung đồng thời gây kết quả không dự đoán được",
        "Client gửi request cùng lúc",
        "Kết nối mạng quá chậm",
      ],
      correct: 1,
      explanation: "Race condition xảy ra khi nhiều thread đọc/ghi cùng dữ liệu mà không đồng bộ, kết quả phụ thuộc thứ tự thực thi.",
    },
    {
      content: "Proxy server có chức năng chính nào?",
      options: [
        "Thay thế DNS server",
        "Trung gian giữa client và server đích, có thể cache và lọc nội dung",
        "Tạo kết nối VPN tự động",
        "Chỉ dùng để tăng tốc download",
      ],
      correct: 1,
      explanation: "Proxy server đóng vai trò trung gian, có thể caching, filtering, logging, ẩn danh cho client.",
    },
    {
      content: "Trong Java NIO, Selector dùng để làm gì?",
      options: [
        "Tạo thread mới cho mỗi kết nối",
        "Giám sát nhiều channel I/O với một thread duy nhất",
        "Mã hóa dữ liệu truyền",
        "Phân giải địa chỉ IP",
      ],
      correct: 1,
      explanation: "Selector cho phép một thread giám sát nhiều channel (socket), là cơ sở của I/O multiplexing trong Java NIO.",
    },
    {
      content: "Mã trạng thái HTTP 401 có nghĩa là gì?",
      options: [
        "Tài nguyên không tồn tại",
        "Chưa xác thực - cần đăng nhập",
        "Server lỗi nội bộ",
        "Yêu cầu quá lớn",
      ],
      correct: 1,
      explanation: "HTTP 401 Unauthorized yêu cầu client xác thực (authentication) trước khi truy cập tài nguyên.",
    },
    {
      content: "Fragmentation trong truyền gói tin IP xảy ra khi nào?",
      options: [
        "Khi server quá tải",
        "Khi kích thước gói tin vượt quá MTU của đường truyền",
        "Khi DNS không phân giải được",
        "Khi TCP timeout",
      ],
      correct: 1,
      explanation: "Fragmentation xảy ra khi gói IP lớn hơn MTU (Maximum Transmission Unit), phải chia nhỏ để truyền.",
    },
    {
      content: "Heartbeat message trong WebSocket dùng để làm gì?",
      options: [
        "Gửi dữ liệu ứng dụng",
        "Kiểm tra kết nối còn sống và ngăn timeout",
        "Mã hóa dữ liệu",
        "Thiết lập kết nối ban đầu",
      ],
      correct: 1,
      explanation: "Heartbeat (ping/pong) duy trì kết nối WebSocket, phát hiện kết nối bị đứt và ngăn proxy/firewall đóng kết nối idle.",
    },
    {
      content: "Token-based authentication (JWT) hoạt động như thế nào?",
      options: [
        "Server lưu session ID trong cơ sở dữ liệu",
        "Client gửi username/password với mỗi request",
        "Server tạo token có chữ ký số, client gửi kèm token trong mỗi request",
        "Client tự tạo token mà không cần server",
      ],
      correct: 2,
      explanation: "JWT: server tạo token chứa thông tin user + chữ ký, client gửi token trong header Authorization mỗi request.",
    },
    {
      content: "Trong lập trình mạng, Big-endian và Little-endian liên quan đến vấn đề gì?",
      options: [
        "Tốc độ mạng",
        "Thứ tự byte khi biểu diễn dữ liệu đa byte",
        "Loại mã hóa",
        "Kích thước buffer",
      ],
      correct: 1,
      explanation: "Endianness là thứ tự byte. Network byte order là Big-endian. Khi truyền mạng cần chuyển đổi đúng endianness.",
    },
    {
      content: "Phương thức HTTP PATCH khác PUT ở điểm nào?",
      options: [
        "PATCH tạo mới tài nguyên, PUT cập nhật",
        "PATCH cập nhật một phần tài nguyên, PUT thay thế toàn bộ",
        "PATCH không có body",
        "PATCH chỉ dùng cho XML",
      ],
      correct: 1,
      explanation: "PATCH cập nhật một phần (partial update) tài nguyên, trong khi PUT thay thế toàn bộ tài nguyên.",
    },
    {
      content: "Trong C#, phương thức NetworkStream.Read() hoạt động như thế nào?",
      options: [
        "Đọc toàn bộ dữ liệu cùng lúc",
        "Đọc một lượng byte vào buffer, trả về số byte thực sự đọc được",
        "Tự động giải mã dữ liệu SSL",
        "Gửi dữ liệu đến server",
      ],
      correct: 1,
      explanation: "NetworkStream.Read() đọc byte vào buffer cho trước, trả về số byte đọc được (có thể ít hơn yêu cầu).",
    },
  ],

  essays: [
    {
      content: "Phân tích chi tiết sự khác biệt giữa blocking I/O, non-blocking I/O và I/O multiplexing. Cho ví dụ mã nguồn minh họa cho mỗi mô hình.",
      explanation: "Blocking: thread bị chặn đến khi I/O xong. Non-blocking: trả về ngay, dùng polling. I/O multiplexing: select/poll/epoll giám sát nhiều fd. Ưu nhược điểm và trường hợp sử dụng phù hợp.",
      points: 4,
    },
    {
      content: "Thiết kế hệ thống chat đơn giản sử dụng socket TCP với kiến trúc Client-Server. Mô tả các thành phần, giao thức giao tiếp và cách xử lý nhiều client đồng thời.",
      explanation: "Server: thread chính accept, tạo thread/client, broadcast message. Client: thread nhận + thread gửi. Protocol: định dạng message, xử lý disconnect, danh sách user online.",
      points: 5,
    },
    {
      content: "Trình bày các mối đe dọa bảo mật phổ biến trong lập trình mạng (Man-in-the-Middle, DDoS, SQL Injection qua API). Đề xuất biện pháp phòng chống cho mỗi loại.",
      explanation: "MITM: dùng TLS, certificate pinning. DDoS: rate limiting, CDN, load balancer. SQL Injection: parameterized queries, input validation. Nêu nguyên lý tấn công và phòng thủ.",
      points: 4,
    },
    {
      content: "So sánh kiến trúc REST và gRPC. Phân tích ưu nhược điểm, hiệu năng, và trường hợp sử dụng phù hợp cho mỗi kiến trúc.",
      explanation: "REST: HTTP/JSON, dễ debug, tương thích web. gRPC: HTTP/2 + Protobuf, nhanh, bidirectional streaming. REST cho public API, gRPC cho microservices nội bộ.",
      points: 3,
    },
    {
      content: "Viết chương trình UDP client-server trong Java/C# để truyền file đơn giản. Giải thích cơ chế đảm bảo dữ liệu toàn vẹn khi dùng UDP.",
      explanation: "Chia file thành chunk, đánh số thứ tự, gửi từng DatagramPacket. Bên nhận gửi ACK. Cơ chế: checksum, sequence number, timeout retransmit. Tại sao UDP cần tự implement reliability.",
      points: 5,
    },
    {
      content: "Giải thích cơ chế hoạt động của WebSocket từ giai đoạn handshake đến khi truyền dữ liệu. So sánh với long-polling và Server-Sent Events.",
      explanation: "WebSocket handshake: HTTP Upgrade → 101 Switching Protocols → full-duplex. Long-polling: client gửi request, server giữ đến có data. SSE: server push one-way. So sánh latency, bandwidth, phức tạp.",
      points: 3,
    },
    {
      content: "Trình bày cơ chế kiểm soát tắc nghẽn (congestion control) trong TCP. Giải thích các thuật toán: Slow Start, Congestion Avoidance, Fast Retransmit và Fast Recovery.",
      explanation: "Slow Start: cwnd tăng gấp đôi mỗi RTT. Congestion Avoidance: tăng tuyến tính sau ngưỡng. Fast Retransmit: retransmit sau 3 duplicate ACK. Fast Recovery: giảm cwnd một nửa thay vì về 1.",
      points: 4,
    },
    {
      content: "Thiết kế REST API cho hệ thống thương mại điện tử đơn giản (sản phẩm, giỏ hàng, đơn hàng). Mô tả endpoint, authentication, error handling và pagination.",
      explanation: "Endpoints: /products, /cart, /orders với CRUD. Auth: JWT Bearer token. Errors: chuẩn hóa format {error, message, code}. Pagination: ?page=1&limit=20. Versioning: /api/v1/.",
      points: 4,
    },
    {
      content: "Phân tích ưu nhược điểm của mô hình microservices so với monolithic trong phát triển ứng dụng mạng. Trình bày cách các service giao tiếp với nhau.",
      explanation: "Monolithic: đơn giản, khó scale. Microservices: scale độc lập, phức tạp vận hành. Giao tiếp: REST, gRPC, message queue (RabbitMQ, Kafka). Service discovery, API gateway, circuit breaker.",
      points: 3,
    },
    {
      content: "Giải thích quy trình xác thực SSL/TLS hai chiều (mutual TLS). Khi nào cần sử dụng mTLS? Viết mã minh họa cấu hình mTLS trong Java/C#.",
      explanation: "mTLS: cả client và server đều xác thực bằng certificate. Quy trình: ServerHello + CertRequest → Client gửi cert → verify cả hai phía. Dùng trong microservices, banking, API nội bộ.",
      points: 4,
    },
  ],
};
