import { Router } from "express";
import authRouter from "./authRouter";
import userRouter from "./userRouter";
import examRouter from "./examRouter";
import examSessionRouter from "./examSessionRouter";
import dashboardRouter from "./dashboardRouter";
import classRouter from "./classRouter";
import adminClassRouter from "./adminClassRouter";
import boardRouter from "./boardRouter";
import predictionRouter from "./predictionRouter";
import passwordResetRouter from "./passwordResetRouter";
import scoreAnalyticsRouter from "./scoreAnalyticsRouter";
import auditLogRouter from "./auditLogRouter";
import systemReportRouter from "./systemReportRouter";
import notificationRouter from "./notificationRouter";
import questionBankRouter from "./questionBankRouter";
import subjectRouter from "./subjectRouter";
import programRouter from "./programRouter";
import subjectGroupRouter from "./subjectGroupRouter";
import examCollaboratorsRouter from "./examCollaboratorsRouter";
import examSharingRouter from "./examSharingRouter";
import exportRouter from "./exportRouter";
import shuffleRouter from "./shuffleRouter";
import teacherStudentsRouter from "./teacherStudentsRouter";
import gradePredictorRouter from "./gradePredictorRouter";

const RouterV1 = Router();

RouterV1.use("/auth", authRouter);
RouterV1.use("/users", userRouter);
RouterV1.use("/dashboard", dashboardRouter);
RouterV1.use("/exams", examRouter);
RouterV1.use("/exam-sessions", examSessionRouter);
RouterV1.use("/classes", classRouter);
RouterV1.use("/admin-classes", adminClassRouter);
RouterV1.use("/board", boardRouter);
RouterV1.use("/prediction", predictionRouter);
RouterV1.use("/password-reset", passwordResetRouter);
RouterV1.use("/score-analytics", scoreAnalyticsRouter);
RouterV1.use("/audit-logs", auditLogRouter);
RouterV1.use("/system-report", systemReportRouter);
RouterV1.use("/notifications", notificationRouter);
RouterV1.use("/question-bank", questionBankRouter);
RouterV1.use("/subjects", subjectRouter);
RouterV1.use("/programs", programRouter);
RouterV1.use("/subject-groups", subjectGroupRouter);
RouterV1.use("/exam-sharing", examSharingRouter);
RouterV1.use("/exam-collaborators", examCollaboratorsRouter);
RouterV1.use("/exports", exportRouter);
RouterV1.use("/shuffle", shuffleRouter);
RouterV1.use("/teacher-students", teacherStudentsRouter);
RouterV1.use("/grade-predictor", gradePredictorRouter);

export default RouterV1;